// Decompiled with JetBrains decompiler
// Type: FriedGinger.DQCheat.SavePlaceListFixer
// Assembly: DQCheat, Version=0.7.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 8257ADC3-8608-472B-A2D6-0B748207D880
// Assembly location: C:\Users\yzsco\Downloads\dq9_save_editor_0.7\DQCheat.dll

using DQ9_Cheat.GameData;
using System.Collections.Generic;

#nullable disable
namespace FriedGinger.DQCheat
{
  public class SavePlaceListFixer
  {
    public static void AddSavePlaces(List<SavePlace> _list)
    {
      _list.Add(new SavePlace((ushort) 109, "Stornway - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 1106, "Angel Falls - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 1202, "Zere - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 1307, "Coffinwell - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 4201, "Alltrades Abbey - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 1506, "Porth Llaffan - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 5801, "Slurry Quay - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 1800, "Dourbridge - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 1903, "Bloomingdale - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 216, "Gleeba - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 2005, "Batsureg - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 2104, "Swinedimples Academy - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 2205, "Wormwood Creek - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 2309, "Upover - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 406, "Gittingham Palace - priest", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 4106, "Observatory - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 4506, "Observatory (after attack) - church", SavePlaceType.Church));
      _list.Add(new SavePlace((ushort) 1100, "Angel Falls - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1101, "Angel Falls - house A", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1102, "Angel Falls - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1103, "Angel Falls - item shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1104, "Angel Falls - stable", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1105, "Angel Falls - mayor's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1107, "Angel Falls - Erinn's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1108, "Angel Falls - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1109, "Angel Falls - mayor's house L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1110, "Angel Falls - Erinn's house L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1112, "Angel Falls - glitched area", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 100, "Stornway - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 103, "Stornway - house A", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 104, "Stornway - weapon shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 105, "Stornway - house B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 106, "Stornway - house C", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 107, "Stornway - armour shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 108, "Stornway - item shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 110, "Stornway - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 112, "Stornway - cellar", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 114, "Stornway Castle - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 115, "Stornway Castle - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 116, "Stornway Castle - B1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 117, "Stornway Castle - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 118, "Stornway Castle - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 119, "Stornway Castle - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 120, "Stornway Castle - L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 121, "Stornway Castle - L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 123, "Stornway Castle - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 124, "Stornway Castle - cellar", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 125, "Stornway Castle - ???", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 198, "Stornway Castle - outside L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50101, "Quester's Rest - Lobby 1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50102, "Quester's Rest - Lounge 1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50103, "Quester's Rest - Guest Room 1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50107, "Quester's Rest - Guardian Fountain", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50108, "Quester's Rest - Royal Suites - Corridor", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50109, "Quester's Rest - Royal Suites - East", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50110, "Quester's Rest - Royal Suites - West", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50201, "Quester's Rest - Lobby 2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50202, "Quester's Rest - Lounge 2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50203, "Quester's Rest - Guest Room 2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50204, "Quester's Rest - Cafeteria 2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50205, "Quester's Rest - Executive Suite 2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50301, "Quester's Rest - Lobby 3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50302, "Quester's Rest - Lounge 3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50303, "Quester's Rest - Guest Room 3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50304, "Quester's Rest - Cafeteria 3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50305, "Quester's Rest - Executive Suite 3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50306, "Quester's Rest - Library 3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50401, "Quester's Rest - Lobby 4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50402, "Quester's Rest - Lounge 4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50403, "Quester's Rest - Guest Room 4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50404, "Quester's Rest - Cafeteria 4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50405, "Quester's Rest - Executive Suite 4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50406, "Quester's Rest - Library 4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50501, "Quester's Rest - Princeton's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50502, "Quester's Rest - Princessa's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50503, "Quester's Rest - Alena's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50504, "Quester's Rest - Kiryl's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50505, "Quester's Rest - Borya's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50506, "Quester's Rest - Meena's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50507, "Quester's Rest - Maya's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50508, "Quester's Rest - Torneko's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50509, "Quester's Rest - Ragnar's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50510, "Quester's Rest - Bianca's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50511, "Quester's Rest - Nera's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50512, "Quester's Rest - Debora's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50513, "Quester's Rest - Milly's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50514, "Quester's Rest - Carver's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50515, "Quester's Rest - Ashlynn's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50516, "Quester's Rest - Kiefer's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50517, "Quester's Rest - Maribel's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50518, "Quester's Rest - Jessica's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50519, "Quester's Rest - Angelo's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50520, "Quester's Rest - Yangus's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50521, "Quester's Rest - Trode's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50522, "Quester's Rest - Morrie's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 50523, "Quester's Rest - Fleurette's room", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1240, "Zere - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1201, "Zere - Petra's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1203, "Zere - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1204, "Zere - house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1205, "Zere - house (cave)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1206, "Zere - underground", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1207, "Zere - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1300, "Coffinwell - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1301, "Coffinwell - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1302, "Coffinwell - house above inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1303, "Coffinwell - house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1304, "Coffinwell - house B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1305, "Coffinwell - house B L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1306, "Coffinwell - weapon/armour shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1308, "Coffinwell - house C", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1309, "Coffinwell - mayor's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1310, "Coffinwell - mayor's house L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1311, "Coffinwell - Phlegming's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1312, "Coffinwell - Phlegming's lab", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1313, "Coffinwell - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4200, "Alltrades Abbey - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4202, "Alltrades Abbey - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1500, "Porth Llaffan - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1501, "Porth Llaffan - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1502, "Porth Llaffan - Jona's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1503, "Porth Llaffan - item shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1504, "Porth Llaffan - weapon/armour shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1505, "Porth Llaffan - mayor's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5800, "Slurry Quay", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1700, "Zere Rocks - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1701, "Zere Rocks - house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1705, "Zere Rocks - house (cave)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1706, "Zere Rocks - underground", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1801, "Dourbridge - house A", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1802, "Dourbridge - house B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1803, "Dourbridge - north house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1804, "Dourbridge - bar", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1805, "Dourbridge - item shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1806, "Dourbridge - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1807, "Dourbridge - tent", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1808, "Dourbridge - secret shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1900, "Bloomingdale - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1901, "Bloomingdale - mayor's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1902, "Bloomingdale - armour shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1904, "Bloomingdale - Bloome mansion", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1905, "Bloomingdale - Bloome mansion L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1906, "Bloomingdale - Bloome mansion courtyard", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1907, "Bloomingdale - house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1908, "Bloomingdale - house B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1909, "Bloomingdale - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1910, "Bloomingdale - inn L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1911, "Bloomingdale - inn B1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1912, "Bloomingdale - old man's bath", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1913, "Bloomingdale - old man's bath B1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1914, "Bloomingdale - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 1915, "Bloomingdale - flashback", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 200, "Gleeba - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 201, "Mirage Mahal - roof", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 202, "Mirage Mahal - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 203, "Mirage Mahal - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 204, "Mirage Mahal - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 205, "Mirage Mahal - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 206, "Mirage Mahal - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 207, "Mirage Mahal - L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 208, "Gleeba - house A", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 209, "Gleeba - house B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 210, "Gleeba - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 211, "Gleeba - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 212, "Gleeba - inn L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 213, "Gleeba - guard post", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 214, "Gleeba - guard post L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 215, "Mirage Mahal - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 219, "Gleeba - dance hall", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2000, "Batsureg - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2001, "Batsureg - weapon/armour shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2002, "Batsureg - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2003, "Batsureg - yurt A", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2004, "Batsureg - yurt B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2006, "Batsureg - yurt C", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2007, "Batsureg - leader's tent", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5600, "Hunters' Yurts", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5601, "Hunters' Yurts - tent A", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5602, "Hunters' Yurts - tent B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2100, "Swinedimples Academy - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2101, "Swinedimples Academy - L1 school hall", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2102, "Swinedimples Academy - L1 corridor", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2103, "Swinedimples Academy - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2105, "Swinedimples Academy - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2106, "Swinedimples Academy - L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2107, "Swinedimples Academy - Dorm. L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2108, "Swinedimples Academy - Dorm. L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2109, "Swinedimples Academy - Dorm. L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2200, "Wormwood Creek - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2201, "Wormwood Creek - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2202, "Wormwood Creek - weapon/armour shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2203, "Wormwood Creek - item shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2204, "Wormwood Creek - house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2205, "Wormwood Creek - well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2300, "Upover - entrance", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2301, "Upover - house A", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2302, "Upover - house B", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2303, "Upover - house C", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2304, "Upover - inn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2305, "Upover - item shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2306, "Upover - weapon shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2307, "Upover - armour shop", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2308, "Upover - mayor's house", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2310, "Upover - underground passage", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2311, "Upover - cave", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 2399, "Upover - glitched area", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5700, "Gortress", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5701, "Gortress - Cells", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5702, "Gortress - Watchtower, L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5703, "Gortress - Watchtower, L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5704, "Gortress - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5705, "Gortress - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5706, "Gortress - B1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5707, "Gortress - event", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 400, "Gittingham Palace", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 401, "Gittingham Palace - L1 South", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 402, "Gittingham Palace - L1 East", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 403, "Gittingham Palace - L1 West", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 404, "Gittingham Palace - L1 North", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 405, "Gittingham Palace - L2 North", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 407, "Gittingham Palace - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 408, "Gittingham Palace - L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 409, "Gittingham Palace - L4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4100, "Observatory", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4101, "Observatory - L1-L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4103, "Observatory - L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4104, "Observatory - L4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4105, "Observatory - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4107, "Observatory - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4109, "Observatory - L3 (interior)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4110, "Observatory - L4 (event)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4300, "Realm of the Almighty - glitched area", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4301, "Realm of the Almighty 1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4302, "Realm of the Almighty 2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4303, "Temple of the Almighty - L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4304, "Temple of the Almighty - L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4305, "Realm of the Almighty - Western Temple", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4306, "Realm of the Almighty - Eastern Temple", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4309, "Temple of the Almighty (flashback)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4500, "Observatory (after attack) (event)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4501, "Observatory (after attack) L1-L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4503, "Observatory (after attack) L3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4504, "Observatory (after attack) L4", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4505, "Observatory (after attack) L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4507, "Observatory (after attack) L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4509, "Observatory (after attack) L3 (interior)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4510, "Observatory (after attack) L3 (event)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4511, "Observatory (after attack) L4 (event)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4512, "Observatory (after attack) L4 (for ending)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 4513, "Observatory (after attack) L2 (flashback)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5101, "Mountain Pass", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5102, "Mountain Pass (event)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5200, "Loch Storn", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5300, "Eastern Checkpoint", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5301, "Eastern Checkpoint - Barracks", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5400, "Hexagon Hill", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5500, "Cuddiedig Cliff", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5900, "Ship - Deck", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5901, "Ship - Captain's Cabin", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5902, "Ship - Passenger Cabin", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 5903, "Ship - Hold", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6000, "Lonely Plains - Mountain Hut", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6001, "Lonely Plains - Mountain Hut (inside)", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6100, "Ulbaruun Cave", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6101, "Ulbaruun Cave - grave", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6200, "Lighthouse", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6201, "Lighthouse L1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6202, "Lighthouse L2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6302, "Hope Springs", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6303, "Hope Springs - cave", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6401, "Starflight Express - Carriage 1", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6402, "Starflight Express - Carriage 2", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6403, "Starflight Express - Carriage 3", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6404, "Starflight Express - ???", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6405, "Starflight Express - glitched area", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 6500, "Wyrmward", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15100, "Island Shrine", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15200, "Way-Out Well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15300, "Pool of Spirits", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15400, "Forest Clearing", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15500, "Nicholas's Cabin", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15600, "Woody Nickitt's House", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15700, "Tree in Lake", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15800, "Sequoia's Hideout", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 15900, "Uhohasis", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16000, "Herman's House", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16100, "Chris Cringle's Cottage", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16200, "Chris Cringle's Paddock", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16300, "Brian's Cave", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16400, "Sealed Well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16500, "Doris's House", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16600, "Monster Research Institute", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16700, "Mountaintop Well - North", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16800, "Mountaintop Well - South", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 16900, "Grand Wizard's Well", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 17000, "Mountain Cave", SavePlaceType.Town));
      _list.Add(new SavePlace((ushort) 10000, "Ocean (aboard ship)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 10100, "Sky (aboard train)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20001, "Angel Falls", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20002, "Western Stornway", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20003, "Zere", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20004, "Doomingale Forest", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20005, "Eastern Coffinwell", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20006, "Western Coffinwell", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20007, "Newid Isle", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20009, "Slurry Coast", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20010, "Bloomingdale", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20011, "Dourbridge", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20012, "Lonely Plains", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20015, "Djust Desert", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20016, "Hermany", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20017, "Pluvi Isle", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20018, "Snowberia", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20019, "Cringle Coast", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20020, "Urdus Marshland", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20021, "Iluugazar Plains", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20022, "Mt Ulzuun", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20023, "Mt Ulbaruun", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20024, "Khaalag Coast", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20025, "Ondor Cliffs", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20026, "Eastern Wormwood", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20027, "Western Wormwood", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20028, "Wormwood Canyon", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20029, "Wyrmtail", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20030, "Wyrmwing", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20032, "Wyrmsmaw", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20033, "Wyrmneck", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20034, "The Gittish Empire", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20038, "Eastern Stornway", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20039, "Snowberian Coast", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20040, "Lonely Coast", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20041, "Newid Isle (east plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20042, "Djust Desert (island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20043, "Angel Falls (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20044, "Eastern Stornway (island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20045, "Western Coffinwell (tower area)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20046, "Djust Desert (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20047, "Hermany (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20048, "Cringle Coast (island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20049, "Urdus Marshland (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20050, "Ondor Cliffs (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20051, "Eastern Wormwood (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20052, "Western Wormwood (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20053, "Wyrmtail (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20054, "Bloomingdale (island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20055, "Western Coffinwell (island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20056, "Lonely Coast (plateau)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20057, "Hermany (island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20058, "Pluvi Isle (small island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20059, "Mt Ulzuun (south)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20060, "Wyrmtail (west)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20061, "Western Wormwood (island)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20062, "Newid Isle (west)", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 20063, "Northern Stornway", SavePlaceType.Field));
      _list.Add(new SavePlace((ushort) 7100, "The Hexagon - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7101, "The Hexagon - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7102, "The Hexagon - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7103, "The Hexagon - B2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7104, "The Hexagon - B1 (upper)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7105, "The Hexagon - B1 (boss)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7301, "Brigadoom - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7302, "Brigadoom - North-Western Tower", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7303, "Brigadoom - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7304, "Brigadoom - Eastern Tower", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7305, "Brigadoom - Western Tower", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7306, "Brigadoom - L2 (throne room)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7307, "Brigadoom - L1 (princess's room)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7400, "Quarantomb - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7401, "Quarantomb - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7402, "Quarantomb - L1 (inside)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7403, "Quarantomb - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9000, "Tower of Trades - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9001, "Tower of Trades - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9002, "Tower of Trades - L2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9003, "Tower of Trades - L3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9004, "Tower of Trades - L4", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9005, "Tower of Trades - L5", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9006, "Tower of Trades - L6", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9007, "Tower of Trades - L7", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9008, "Tower of Trades - ???", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7601, "Tywll Cave", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7602, "Tywll Cave - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7603, "Tywll Cave - L1 (cave)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7604, "Tywll Cave - L2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7605, "Tywll Cave - L2 (part 2)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7700, "Heights of Loneliness - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7701, "Heights of Loneliness - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7702, "Heights of Loneliness - L2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7703, "Heights of Loneliness - L3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7704, "Heights of Loneliness - L4", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7705, "Heights of Loneliness - L5", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7706, "Heights of Loneliness - L6", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7707, "Heights of Loneliness - L7", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7708, "Heights of Loneliness - L6 (unused area)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7709, "Heights of Loneliness - L7 (outside)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7900, "The Bad Cave - Entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7901, "The Bad Cave - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7902, "The Bad Cave - L1 (hideout)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7903, "The Bad Cave - L1 (part 2)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7904, "The Bad Cave - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7905, "The Bad Cave - B2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7906, "The Bad Cave - B2 (boss)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7802, "The Plumbed Depths - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7803, "The Plumbed Depths - B1 (second area)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7804, "The Plumbed Depths - B1 (room)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7805, "The Plumbed Depths - B2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7806, "The Plumbed Depths - B3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7807, "The Plumbed Depths - B1 (dungeon)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7808, "The Plumbed Depths - B2 (graves)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 7809, "The Plumbed Depths - B3 (hideout)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8201, "Gerzuun - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8202, "Gerzuun - tent A", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8203, "Gerzuun - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8204, "Gerzuun - tent B", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8205, "Gerzuun - well", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8206, "Gerzuun - tent C", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8207, "Gerzuun - Underground Passage", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8208, "Gerzuun - Underground Spring", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8301, "Swinedimples - The Old School, B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8302, "Swinedimples - The Old School, B2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8303, "Swinedimples - The Old School, B2 (classroom)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8400, "The Bowhole - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8401, "The Bowhole - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8402, "The Bowhole - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8403, "The Bowhole - L1 (side room)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8404, "The Bowhole - B2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8405, "The Bowhole - B3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8406, "The Bowhole - B4", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8407, "The Bowhole - B4 (boss)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8602, "The Magmaroo - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8603, "The Magmaroo - L1 (outside)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8604, "The Magmaroo - L2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8605, "The Magmaroo - L3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8606, "The Magmaroo - L3 (outside)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8607, "The Magmaroo - L3 (second cave)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8608, "The Magmaroo - L4", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8609, "The Magmaroo - L5", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8610, "The Magmaroo - L5 (outside)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8611, "The Magmaroo - L6", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8612, "The Magmaroo - Summit", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8613, "The Magmaroo - Greygnarl's Lair", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8701, "Oubliette - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8702, "Oubliette - B2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8703, "Oubliette - B3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8704, "Oubliette - B4", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8705, "Oubliette - B5", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8706, "Oubliette - B6", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 8707, "Oubliette - event", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4400, "Realm of the Mighty - entrance", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4401, "Realm of the Mighty - outside L6", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4402, "Realm of the Mighty - outside L8", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4403, "Realm of the Mighty - red sphere", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4404, "Realm of the Mighty - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4405, "Realm of the Mighty - B1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4406, "Realm of the Mighty - B2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4407, "Realm of the Mighty - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4408, "Realm of the Mighty - L2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4409, "Realm of the Mighty - L3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4410, "Realm of the Mighty - L4", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4411, "Realm of the Mighty - L5", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4412, "Realm of the Mighty - L1 (right room)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4413, "Realm of the Mighty - L6", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4414, "Realm of the Mighty - L8", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4416, "Realm of the Mighty - L8 (left corridor)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4417, "Realm of the Mighty - L9 (left room)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4418, "Realm of the Mighty - L9 (right room)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4419, "Realm of the Mighty - L8 (right corridor)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4420, "Realm of the Mighty - L10", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4421, "Realm of the Mighty - L11", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4422, "Palace of the Mighty", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4423, "Palace of the Mighty, L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4424, "Palace of the Mighty, L2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 4499, "Realm of the Mighty (event)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9101, "Tower of Nod - L1", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9102, "Tower of Nod - L2", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9103, "Tower of Nod - L3", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9104, "Tower of Nod - L4", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9105, "Tower of Nod - L5", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9106, "Tower of Nod - L5 (outside)", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9107, "Tower of Nod - L6", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 9108, "Tower of Nod - L7", SavePlaceType.Dungeon));
      SavePlaceListFixer.AddGrottoLocations(_list, (ushort) 40001, "Grotto");
      SavePlaceListFixer.AddGrottoLocations(_list, (ushort) 40021, "Grotto");
      SavePlaceListFixer.AddGrottoLocations(_list, (ushort) 40041, "Grotto");
      SavePlaceListFixer.AddGrottoLocations(_list, (ushort) 40061, "Grotto");
      SavePlaceListFixer.AddGrottoLocations(_list, (ushort) 40081, "Grotto");
      _list.Add(new SavePlace((ushort) 41101, "Grotto (Caves) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41104, "Grotto (Caves) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41203, "Grotto (Ruins) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41205, "Grotto (Ruins) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41301, "Grotto (Ice) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41302, "Grotto (Ice) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41401, "Grotto (Water) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41402, "Grotto (Water) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41503, "Grotto (Volcano) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 41505, "Grotto (Volcano) - Boss", SavePlaceType.Dungeon));
      _list.Add(new SavePlace((ushort) 1, "Debug Floor", SavePlaceType.Other));
      _list.Add(new SavePlace((ushort) 3, "Monster Modify", SavePlaceType.Other));
      _list.Add(new SavePlace((ushort) 19999, "Encounter Test", SavePlaceType.Other));
      _list.Add(new SavePlace((ushort) 20000, "Bed Test", SavePlaceType.Other));
      _list.Add(new SavePlace((ushort) 20101, "Angel Falls (opening)", SavePlaceType.Other));
      _list.Add(new SavePlace((ushort) 20102, "Angel Falls (ending)", SavePlaceType.Other));
      _list.Add(new SavePlace((ushort) 20111, "Bloomingdale (ending)", SavePlaceType.Other));
      _list.Add(new SavePlace((ushort) 20207, "Newid Isle (ending)", SavePlaceType.Other));
      _list.Add(new SavePlace(ushort.MaxValue, "Newid Isle (after ending)", SavePlaceType.Other));
    }

    private static void AddGrottoLocations(List<SavePlace> _list, ushort index, string type)
    {
      int num = 1;
      while (num <= 16)
      {
        _list.Add(new SavePlace(index, type + " - B" + num.ToString(), SavePlaceType.Dungeon));
        ++num;
        ++index;
      }
    }
  }
}
