// Decompiled with JetBrains decompiler
// Type: DQ9_Cheat.GameData.MonsterDataList
// Assembly: DQ9_Cheat, Version=0.7.0.57, Culture=neutral, PublicKeyToken=null
// MVID: 9E5BE672-CBE6-45FB-AC35-96531044560E
// Assembly location: C:\Users\yzsco\Downloads\dq9_save_editor_0.7\DQCheat.Patched.0.7.exe

using System.Collections.ObjectModel;

#nullable disable
namespace DQ9_Cheat.GameData
{
  internal static class MonsterDataList
  {
    private static System.Collections.Generic.List<string> _list = new System.Collections.Generic.List<string>();

    static MonsterDataList()
    {
      MonsterDataList._list.Add("Slime");
      MonsterDataList._list.Add("Cruelcumber");
      MonsterDataList._list.Add("Teeny sanguini");
      MonsterDataList._list.Add("Sacksquatch");
      MonsterDataList._list.Add("Batterfly");
      MonsterDataList._list.Add("Dracky");
      MonsterDataList._list.Add("Bodkin archer");
      MonsterDataList._list.Add("Bag o' laughs");
      MonsterDataList._list.Add("Mecha-mynah");
      MonsterDataList._list.Add("Firespirit");
      MonsterDataList._list.Add("Spirit");
      MonsterDataList._list.Add("Winkster");
      MonsterDataList._list.Add("Hammerhood");
      MonsterDataList._list.Add("She-slime");
      MonsterDataList._list.Add("Funghoul");
      MonsterDataList._list.Add("Bubble slime");
      MonsterDataList._list.Add("Wooper trooper");
      MonsterDataList._list.Add("Betterfly");
      MonsterDataList._list.Add("Meowgician");
      MonsterDataList._list.Add("Ragged reaper");
      MonsterDataList._list.Add("Gastropog");
      MonsterDataList._list.Add("Brownie");
      MonsterDataList._list.Add("Boppin' badger");
      MonsterDataList._list.Add("Drackmage");
      MonsterDataList._list.Add("Bodkin fletcher");
      MonsterDataList._list.Add("Ram raider");
      MonsterDataList._list.Add("Cumaulus");
      MonsterDataList._list.Add("Skeleton");
      MonsterDataList._list.Add("Healslime");
      MonsterDataList._list.Add("Blinkster");
      MonsterDataList._list.Add("Leery lout");
      MonsterDataList._list.Add("Lunatick");
      MonsterDataList._list.Add("Leafy larrikin");
      MonsterDataList._list.Add("Clockwork cuckoo");
      MonsterDataList._list.Add("Slugger");
      MonsterDataList._list.Add("Chariot chappie");
      MonsterDataList._list.Add("Morphean mushroom");
      MonsterDataList._list.Add("Lost soul");
      MonsterDataList._list.Add("Flython");
      MonsterDataList._list.Add("Badger mager");
      MonsterDataList._list.Add("Crabid");
      MonsterDataList._list.Add("Mean spirit");
      MonsterDataList._list.Add("Magus");
      MonsterDataList._list.Add("Mummy boy");
      MonsterDataList._list.Add("Earthenwarrior");
      MonsterDataList._list.Add("Metal slime");
      MonsterDataList._list.Add("Bodkin bowyer");
      MonsterDataList._list.Add("Slime knight");
      MonsterDataList._list.Add("Cyclown");
      MonsterDataList._list.Add("Badboon");
      MonsterDataList._list.Add("Slime stack");
      MonsterDataList._list.Add("Mudraker");
      MonsterDataList._list.Add("Mushroom mage");
      MonsterDataList._list.Add("Drackyma");
      MonsterDataList._list.Add("Walking corpse");
      MonsterDataList._list.Add("Jinkster");
      MonsterDataList._list.Add("Restless armour");
      MonsterDataList._list.Add("Knocktopus");
      MonsterDataList._list.Add("Chimaera");
      MonsterDataList._list.Add("Salamarauder");
      MonsterDataList._list.Add("Man o' war");
      MonsterDataList._list.Add("Mortoad");
      MonsterDataList._list.Add("Dread admiral");
      MonsterDataList._list.Add("Zumeanie");
      MonsterDataList._list.Add("Bud brother");
      MonsterDataList._list.Add("Spinchilla");
      MonsterDataList._list.Add("Bewarewolf");
      MonsterDataList._list.Add("Clawcerer");
      MonsterDataList._list.Add("Rampage");
      MonsterDataList._list.Add("Beakon");
      MonsterDataList._list.Add("Mad moai");
      MonsterDataList._list.Add("Trigertaur");
      MonsterDataList._list.Add("Grinade");
      MonsterDataList._list.Add("Toxic zombie");
      MonsterDataList._list.Add("Metal slime knight");
      MonsterDataList._list.Add("Hocus chimaera");
      MonsterDataList._list.Add("Treeface");
      MonsterDataList._list.Add("Stone golem");
      MonsterDataList._list.Add("Gum shield");
      MonsterDataList._list.Add("Pink sanguini");
      MonsterDataList._list.Add("Scarewolf");
      MonsterDataList._list.Add("Big badboon");
      MonsterDataList._list.Add("Medislime");
      MonsterDataList._list.Add("Shaman");
      MonsterDataList._list.Add("Weakon beakon");
      MonsterDataList._list.Add("Raving lunatick");
      MonsterDataList._list.Add("Hunter mech");
      MonsterDataList._list.Add("Riptide");
      MonsterDataList._list.Add("Metal medley");
      MonsterDataList._list.Add("King slime");
      MonsterDataList._list.Add("Claw hammer");
      MonsterDataList._list.Add("Shocktopus");
      MonsterDataList._list.Add("Axolhotl");
      MonsterDataList._list.Add("Parched peckerel");
      MonsterDataList._list.Add("Power hammer");
      MonsterDataList._list.Add("Gold golem");
      MonsterDataList._list.Add("Expload");
      MonsterDataList._list.Add("Mummy");
      MonsterDataList._list.Add("Admirer");
      MonsterDataList._list.Add("Lesionnaire");
      MonsterDataList._list.Add("Diethon");
      MonsterDataList._list.Add("Purrestidigitator");
      MonsterDataList._list.Add("Manguini");
      MonsterDataList._list.Add("Mandrake major");
      MonsterDataList._list.Add("Scourgette");
      MonsterDataList._list.Add("Wyrtle");
      MonsterDataList._list.Add("Crabber dabber doo");
      MonsterDataList._list.Add("Badja");
      MonsterDataList._list.Add("Giddy gastropog");
      MonsterDataList._list.Add("Treevil");
      MonsterDataList._list.Add("Ghoul");
      MonsterDataList._list.Add("Robo-robin");
      MonsterDataList._list.Add("Swinoceros");
      MonsterDataList._list.Add("Peckerel");
      MonsterDataList._list.Add("Battering ram");
      MonsterDataList._list.Add("Rockbomb");
      MonsterDataList._list.Add("Brainy badboon");
      MonsterDataList._list.Add("Drackal");
      MonsterDataList._list.Add("Gruffon");
      MonsterDataList._list.Add("Sorcerer");
      MonsterDataList._list.Add("Cheeky tiki");
      MonsterDataList._list.Add("Deadcurion");
      MonsterDataList._list.Add("Infernal armour");
      MonsterDataList._list.Add("Troll");
      MonsterDataList._list.Add("Shivery shrubbery");
      MonsterDataList._list.Add("Tearwolf");
      MonsterDataList._list.Add("Brrearthenwarrior");
      MonsterDataList._list.Add("Apeckalypse");
      MonsterDataList._list.Add("Great gruffon");
      MonsterDataList._list.Add("White trigertaur");
      MonsterDataList._list.Add("Sootheslime");
      MonsterDataList._list.Add("Icikiller");
      MonsterDataList._list.Add("Teaky mask");
      MonsterDataList._list.Add("Raving reaper");
      MonsterDataList._list.Add("Wight priest");
      MonsterDataList._list.Add("Sculptrice");
      MonsterDataList._list.Add("Handsome crab");
      MonsterDataList._list.Add("Sail serpent");
      MonsterDataList._list.Add("Grim grinner");
      MonsterDataList._list.Add("Sluggernaut");
      MonsterDataList._list.Add("Splatterhorn");
      MonsterDataList._list.Add("Whirly girly");
      MonsterDataList._list.Add("Gramarye gruffon");
      MonsterDataList._list.Add("Skeleton soldier");
      MonsterDataList._list.Add("Bloody manguini");
      MonsterDataList._list.Add("Blood mummy");
      MonsterDataList._list.Add("Harmour");
      MonsterDataList._list.Add("Python priest");
      MonsterDataList._list.Add("Sculpture vulture");
      MonsterDataList._list.Add("Living statue");
      MonsterDataList._list.Add("Goodybag");
      MonsterDataList._list.Add("Drakularge");
      MonsterDataList._list.Add("Liquid metal slime");
      MonsterDataList._list.Add("Moosifer");
      MonsterDataList._list.Add("Drastic drackal");
      MonsterDataList._list.Add("Terrorhawk");
      MonsterDataList._list.Add("Cyclops");
      MonsterDataList._list.Add("Cumulus rex");
      MonsterDataList._list.Add("Bomboulder");
      MonsterDataList._list.Add("Bagma");
      MonsterDataList._list.Add("Golem");
      MonsterDataList._list.Add("Seasaur");
      MonsterDataList._list.Add("Hell niño");
      MonsterDataList._list.Add("Corrupt carter");
      MonsterDataList._list.Add("Live lava");
      MonsterDataList._list.Add("Mandrake marauder");
      MonsterDataList._list.Add("Mega moai");
      MonsterDataList._list.Add("Magmalice");
      MonsterDataList._list.Add("Green dragon");
      MonsterDataList._list.Add("Abyss diver");
      MonsterDataList._list.Add("Stenchurion");
      MonsterDataList._list.Add("Gloomy gastropog");
      MonsterDataList._list.Add("Dark skeleton");
      MonsterDataList._list.Add("Killing machine");
      MonsterDataList._list.Add("Dreadful drackal");
      MonsterDataList._list.Add("Lethal armour");
      MonsterDataList._list.Add("Freezing fog");
      MonsterDataList._list.Add("Stone guardian");
      MonsterDataList._list.Add("Boss troll");
      MonsterDataList._list.Add("Blastoad");
      MonsterDataList._list.Add("Fright knight");
      MonsterDataList._list.Add("Wight king");
      MonsterDataList._list.Add("Claws");
      MonsterDataList._list.Add("Aggrosculpture");
      MonsterDataList._list.Add("Mandrake marshal");
      MonsterDataList._list.Add("Bad karmour");
      MonsterDataList._list.Add("Wyrtoise");
      MonsterDataList._list.Add("King crab");
      MonsterDataList._list.Add("Genie sanguini");
      MonsterDataList._list.Add("Cumulus vex");
      MonsterDataList._list.Add("Red dragon");
      MonsterDataList._list.Add("Gigantes");
      MonsterDataList._list.Add("Belisha beakon");
      MonsterDataList._list.Add("Charmour");
      MonsterDataList._list.Add("Cureslime");
      MonsterDataList._list.Add("Great troll");
      MonsterDataList._list.Add("Cobra cardinal");
      MonsterDataList._list.Add("Prism peacock");
      MonsterDataList._list.Add("Night knight");
      MonsterDataList._list.Add("Drakulard");
      MonsterDataList._list.Add("Barbatos");
      MonsterDataList._list.Add("Firn fiend");
      MonsterDataList._list.Add("Sick trigertaur");
      MonsterDataList._list.Add("Cannibox");
      MonsterDataList._list.Add("Mimic");
      MonsterDataList._list.Add("King cureslime");
      MonsterDataList._list.Add("Gem jamboree");
      MonsterDataList._list.Add("Sluggerslaught");
      MonsterDataList._list.Add("Terror troll");
      MonsterDataList._list.Add("Cosmic chimaera");
      MonsterDataList._list.Add("Wishmaster");
      MonsterDataList._list.Add("Cumulus hex");
      MonsterDataList._list.Add("Stale whale");
      MonsterDataList._list.Add("Metal king slime");
      MonsterDataList._list.Add("Slionheart");
      MonsterDataList._list.Add("Godsteed");
      MonsterDataList._list.Add("Wonder wyrtle");
      MonsterDataList._list.Add("Widow's pique");
      MonsterDataList._list.Add("Octagoon");
      MonsterDataList._list.Add("Darkonium slime");
      MonsterDataList._list.Add("Freaky tiki");
      MonsterDataList._list.Add("Alarmour");
      MonsterDataList._list.Add("Boa bishop");
      MonsterDataList._list.Add("Cyber spider");
      MonsterDataList._list.Add("Alphyn");
      MonsterDataList._list.Add("Gem slime");
      MonsterDataList._list.Add("AU-1000");
      MonsterDataList._list.Add("Void droid");
      MonsterDataList._list.Add("Platinum king jewel");
      MonsterDataList._list.Add("Cannibelle");
      MonsterDataList._list.Add("Grim reaper");
      MonsterDataList._list.Add("Wight emperor");
      MonsterDataList._list.Add("Grrrgoyle");
      MonsterDataList._list.Add("Pandora's box");
      MonsterDataList._list.Add("Uncommon cold");
      MonsterDataList._list.Add("Geothaum");
      MonsterDataList._list.Add("Blight knight");
      MonsterDataList._list.Add("Flamin' drayman");
      MonsterDataList._list.Add("Tantamount");
      MonsterDataList._list.Add("Barriearthenwarrior");
      MonsterDataList._list.Add("Bird of terrordise");
      MonsterDataList._list.Add("Scarlet fever");
      MonsterDataList._list.Add("Hell's gatekeeper");
      MonsterDataList._list.Add("Rashaverak");
      MonsterDataList._list.Add("Master moosifer");
      MonsterDataList._list.Add("Vermil lion");
      MonsterDataList._list.Add("Slugly betsy");
      MonsterDataList._list.Add("Moai minstrel");
      MonsterDataList._list.Add("Boogie manguini");
      MonsterDataList._list.Add("Mandrake monarch");
      MonsterDataList._list.Add("Bling badger");
      MonsterDataList._list.Add("Prime slime");
      MonsterDataList._list.Add("Hammer horror");
      MonsterDataList._list.Add("Drakulord");
      MonsterDataList._list.Add("Pale whale");
      MonsterDataList._list.Add("Seavern");
      MonsterDataList._list.Add("Hexagoon");
      MonsterDataList._list.Add("Wight Knight");
      MonsterDataList._list.Add("Morag");
      MonsterDataList._list.Add("Ragin' Contagion");
      MonsterDataList._list.Add("Master of Nu'un");
      MonsterDataList._list.Add("Lleviathan");
      MonsterDataList._list.Add("Garth Goyle");
      MonsterDataList._list.Add("Tyrantula");
      MonsterDataList._list.Add("Grand Lizzier");
      MonsterDataList._list.Add("Larstastnaras");
      MonsterDataList._list.Add("Dreadmaster");
      MonsterDataList._list.Add("Gadrongo");
      MonsterDataList._list.Add("Greygnarl");
      MonsterDataList._list.Add("Goreham-Hogg");
      MonsterDataList._list.Add("Hootingham-Gore");
      MonsterDataList._list.Add("Goresby-Purrvis");
      MonsterDataList._list.Add("King Godwyn");
      MonsterDataList._list.Add("King Godwyn");
      MonsterDataList._list.Add("Barbarus");
      MonsterDataList._list.Add("Corvus");
      MonsterDataList._list.Add("Corvus");
      MonsterDataList._list.Add("Yore");
      MonsterDataList._list.Add("Rover");
      MonsterDataList._list.Add("King Godfrey");
      MonsterDataList._list.Add("Tyrannosaura Wrecks");
      MonsterDataList._list.Add("Nodoph");
      MonsterDataList._list.Add("Equinox");
      MonsterDataList._list.Add("Nemean");
      MonsterDataList._list.Add("Shogum");
      MonsterDataList._list.Add("Trauminator");
      MonsterDataList._list.Add("Elusid");
      MonsterDataList._list.Add("Sir Sanguinus");
      MonsterDataList._list.Add("Atlas");
      MonsterDataList._list.Add("Hammibal");
      MonsterDataList._list.Add("Fowleye");
      MonsterDataList._list.Add("Excalipurr");
      MonsterDataList._list.Add("Tyrannosaurus Wrecks");
      MonsterDataList._list.Add("Greygnarl");
      MonsterDataList._list.Add("Dragonlord");
      MonsterDataList._list.Add("Malroth");
      MonsterDataList._list.Add("Baramos");
      MonsterDataList._list.Add("Zoma");
      MonsterDataList._list.Add("Psaro");
      MonsterDataList._list.Add("Estark");
      MonsterDataList._list.Add("Nimzo");
      MonsterDataList._list.Add("Murdaw");
      MonsterDataList._list.Add("Mortamor");
      MonsterDataList._list.Add("Nokturnus");
      MonsterDataList._list.Add("Orgodemir");
      MonsterDataList._list.Add("Dhoulmagus");
      MonsterDataList._list.Add("Rhapthorne");
    }

    public static ReadOnlyCollection<string> List => MonsterDataList._list.AsReadOnly();
  }
}
