// Decompiled with JetBrains decompiler
// Type: DQ9_Cheat.GameData.MonsterDataList
// Assembly: DQ9_Cheat, Version=0.7.0.57, Culture=neutral, PublicKeyToken=null
// MVID: 9E5BE672-CBE6-45FB-AC35-96531044560E
// Assembly location: dq9_save_editor_0.7\DQCheat.Patched.0.7.exe

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace DQ9_Cheat.GameData;

internal static class MonsterDataList
{
    private static readonly List<string> _list = new();

    static MonsterDataList()
    {
        _list.Add("Slime");
        _list.Add("Cruelcumber");
        _list.Add("Teeny sanguini");
        _list.Add("Sacksquatch");
        _list.Add("Batterfly");
        _list.Add("Dracky");
        _list.Add("Bodkin archer");
        _list.Add("Bag o' laughs");
        _list.Add("Mecha-mynah");
        _list.Add("Firespirit");
        _list.Add("Spirit");
        _list.Add("Winkster");
        _list.Add("Hammerhood");
        _list.Add("She-slime");
        _list.Add("Funghoul");
        _list.Add("Bubble slime");
        _list.Add("Wooper trooper");
        _list.Add("Betterfly");
        _list.Add("Meowgician");
        _list.Add("Ragged reaper");
        _list.Add("Gastropog");
        _list.Add("Brownie");
        _list.Add("Boppin' badger");
        _list.Add("Drackmage");
        _list.Add("Bodkin fletcher");
        _list.Add("Ram raider");
        _list.Add("Cumaulus");
        _list.Add("Skeleton");
        _list.Add("Healslime");
        _list.Add("Blinkster");
        _list.Add("Leery lout");
        _list.Add("Lunatick");
        _list.Add("Leafy larrikin");
        _list.Add("Clockwork cuckoo");
        _list.Add("Slugger");
        _list.Add("Chariot chappie");
        _list.Add("Morphean mushroom");
        _list.Add("Lost soul");
        _list.Add("Flython");
        _list.Add("Badger mager");
        _list.Add("Crabid");
        _list.Add("Mean spirit");
        _list.Add("Magus");
        _list.Add("Mummy boy");
        _list.Add("Earthenwarrior");
        _list.Add("Metal slime");
        _list.Add("Bodkin bowyer");
        _list.Add("Slime knight");
        _list.Add("Cyclown");
        _list.Add("Badboon");
        _list.Add("Slime stack");
        _list.Add("Mudraker");
        _list.Add("Mushroom mage");
        _list.Add("Drackyma");
        _list.Add("Walking corpse");
        _list.Add("Jinkster");
        _list.Add("Restless armour");
        _list.Add("Knocktopus");
        _list.Add("Chimaera");
        _list.Add("Salamarauder");
        _list.Add("Man o' war");
        _list.Add("Mortoad");
        _list.Add("Dread admiral");
        _list.Add("Zumeanie");
        _list.Add("Bud brother");
        _list.Add("Spinchilla");
        _list.Add("Bewarewolf");
        _list.Add("Clawcerer");
        _list.Add("Rampage");
        _list.Add("Beakon");
        _list.Add("Mad moai");
        _list.Add("Trigertaur");
        _list.Add("Grinade");
        _list.Add("Toxic zombie");
        _list.Add("Metal slime knight");
        _list.Add("Hocus chimaera");
        _list.Add("Treeface");
        _list.Add("Stone golem");
        _list.Add("Gum shield");
        _list.Add("Pink sanguini");
        _list.Add("Scarewolf");
        _list.Add("Big badboon");
        _list.Add("Medislime");
        _list.Add("Shaman");
        _list.Add("Weakon beakon");
        _list.Add("Raving lunatick");
        _list.Add("Hunter mech");
        _list.Add("Riptide");
        _list.Add("Metal medley");
        _list.Add("King slime");
        _list.Add("Claw hammer");
        _list.Add("Shocktopus");
        _list.Add("Axolhotl");
        _list.Add("Parched peckerel");
        _list.Add("Power hammer");
        _list.Add("Gold golem");
        _list.Add("Expload");
        _list.Add("Mummy");
        _list.Add("Admirer");
        _list.Add("Lesionnaire");
        _list.Add("Diethon");
        _list.Add("Purrestidigitator");
        _list.Add("Manguini");
        _list.Add("Mandrake major");
        _list.Add("Scourgette");
        _list.Add("Wyrtle");
        _list.Add("Crabber dabber doo");
        _list.Add("Badja");
        _list.Add("Giddy gastropog");
        _list.Add("Treevil");
        _list.Add("Ghoul");
        _list.Add("Robo-robin");
        _list.Add("Swinoceros");
        _list.Add("Peckerel");
        _list.Add("Battering ram");
        _list.Add("Rockbomb");
        _list.Add("Brainy badboon");
        _list.Add("Drackal");
        _list.Add("Gruffon");
        _list.Add("Sorcerer");
        _list.Add("Cheeky tiki");
        _list.Add("Deadcurion");
        _list.Add("Infernal armour");
        _list.Add("Troll");
        _list.Add("Shivery shrubbery");
        _list.Add("Tearwolf");
        _list.Add("Brrearthenwarrior");
        _list.Add("Apeckalypse");
        _list.Add("Great gruffon");
        _list.Add("White trigertaur");
        _list.Add("Sootheslime");
        _list.Add("Icikiller");
        _list.Add("Teaky mask");
        _list.Add("Raving reaper");
        _list.Add("Wight priest");
        _list.Add("Sculptrice");
        _list.Add("Handsome crab");
        _list.Add("Sail serpent");
        _list.Add("Grim grinner");
        _list.Add("Sluggernaut");
        _list.Add("Splatterhorn");
        _list.Add("Whirly girly");
        _list.Add("Gramarye gruffon");
        _list.Add("Skeleton soldier");
        _list.Add("Bloody manguini");
        _list.Add("Blood mummy");
        _list.Add("Harmour");
        _list.Add("Python priest");
        _list.Add("Sculpture vulture");
        _list.Add("Living statue");
        _list.Add("Goodybag");
        _list.Add("Drakularge");
        _list.Add("Liquid metal slime");
        _list.Add("Moosifer");
        _list.Add("Drastic drackal");
        _list.Add("Terrorhawk");
        _list.Add("Cyclops");
        _list.Add("Cumulus rex");
        _list.Add("Bomboulder");
        _list.Add("Bagma");
        _list.Add("Golem");
        _list.Add("Seasaur");
        _list.Add("Hell niño");
        _list.Add("Corrupt carter");
        _list.Add("Live lava");
        _list.Add("Mandrake marauder");
        _list.Add("Mega moai");
        _list.Add("Magmalice");
        _list.Add("Green dragon");
        _list.Add("Abyss diver");
        _list.Add("Stenchurion");
        _list.Add("Gloomy gastropog");
        _list.Add("Dark skeleton");
        _list.Add("Killing machine");
        _list.Add("Dreadful drackal");
        _list.Add("Lethal armour");
        _list.Add("Freezing fog");
        _list.Add("Stone guardian");
        _list.Add("Boss troll");
        _list.Add("Blastoad");
        _list.Add("Fright knight");
        _list.Add("Wight king");
        _list.Add("Claws");
        _list.Add("Aggrosculpture");
        _list.Add("Mandrake marshal");
        _list.Add("Bad karmour");
        _list.Add("Wyrtoise");
        _list.Add("King crab");
        _list.Add("Genie sanguini");
        _list.Add("Cumulus vex");
        _list.Add("Red dragon");
        _list.Add("Gigantes");
        _list.Add("Belisha beakon");
        _list.Add("Charmour");
        _list.Add("Cureslime");
        _list.Add("Great troll");
        _list.Add("Cobra cardinal");
        _list.Add("Prism peacock");
        _list.Add("Night knight");
        _list.Add("Drakulard");
        _list.Add("Barbatos");
        _list.Add("Firn fiend");
        _list.Add("Sick trigertaur");
        _list.Add("Cannibox");
        _list.Add("Mimic");
        _list.Add("King cureslime");
        _list.Add("Gem jamboree");
        _list.Add("Sluggerslaught");
        _list.Add("Terror troll");
        _list.Add("Cosmic chimaera");
        _list.Add("Wishmaster");
        _list.Add("Cumulus hex");
        _list.Add("Stale whale");
        _list.Add("Metal king slime");
        _list.Add("Slionheart");
        _list.Add("Godsteed");
        _list.Add("Wonder wyrtle");
        _list.Add("Widow's pique");
        _list.Add("Octagoon");
        _list.Add("Darkonium slime");
        _list.Add("Freaky tiki");
        _list.Add("Alarmour");
        _list.Add("Boa bishop");
        _list.Add("Cyber spider");
        _list.Add("Alphyn");
        _list.Add("Gem slime");
        _list.Add("AU-1000");
        _list.Add("Void droid");
        _list.Add("Platinum king jewel");
        _list.Add("Cannibelle");
        _list.Add("Grim reaper");
        _list.Add("Wight emperor");
        _list.Add("Grrrgoyle");
        _list.Add("Pandora's box");
        _list.Add("Uncommon cold");
        _list.Add("Geothaum");
        _list.Add("Blight knight");
        _list.Add("Flamin' drayman");
        _list.Add("Tantamount");
        _list.Add("Barriearthenwarrior");
        _list.Add("Bird of terrordise");
        _list.Add("Scarlet fever");
        _list.Add("Hell's gatekeeper");
        _list.Add("Rashaverak");
        _list.Add("Master moosifer");
        _list.Add("Vermil lion");
        _list.Add("Slugly betsy");
        _list.Add("Moai minstrel");
        _list.Add("Boogie manguini");
        _list.Add("Mandrake monarch");
        _list.Add("Bling badger");
        _list.Add("Prime slime");
        _list.Add("Hammer horror");
        _list.Add("Drakulord");
        _list.Add("Pale whale");
        _list.Add("Seavern");
        _list.Add("Hexagoon");
        _list.Add("Wight Knight");
        _list.Add("Morag");
        _list.Add("Ragin' Contagion");
        _list.Add("Master of Nu'un");
        _list.Add("Lleviathan");
        _list.Add("Garth Goyle");
        _list.Add("Tyrantula");
        _list.Add("Grand Lizzier");
        _list.Add("Larstastnaras");
        _list.Add("Dreadmaster");
        _list.Add("Gadrongo");
        _list.Add("Greygnarl");
        _list.Add("Goreham-Hogg");
        _list.Add("Hootingham-Gore");
        _list.Add("Goresby-Purrvis");
        _list.Add("King Godwyn");
        _list.Add("King Godwyn");
        _list.Add("Barbarus");
        _list.Add("Corvus");
        _list.Add("Corvus");
        _list.Add("Yore");
        _list.Add("Rover");
        _list.Add("King Godfrey");
        _list.Add("Tyrannosaura Wrecks");
        _list.Add("Nodoph");
        _list.Add("Equinox");
        _list.Add("Nemean");
        _list.Add("Shogum");
        _list.Add("Trauminator");
        _list.Add("Elusid");
        _list.Add("Sir Sanguinus");
        _list.Add("Atlas");
        _list.Add("Hammibal");
        _list.Add("Fowleye");
        _list.Add("Excalipurr");
        _list.Add("Tyrannosaurus Wrecks");
        _list.Add("Greygnarl");
        _list.Add("Dragonlord");
        _list.Add("Malroth");
        _list.Add("Baramos");
        _list.Add("Zoma");
        _list.Add("Psaro");
        _list.Add("Estark");
        _list.Add("Nimzo");
        _list.Add("Murdaw");
        _list.Add("Mortamor");
        _list.Add("Nokturnus");
        _list.Add("Orgodemir");
        _list.Add("Dhoulmagus");
        _list.Add("Rhapthorne");
    }

    public static ReadOnlyCollection<string> List => _list.AsReadOnly();
}