// Decompiled with JetBrains decompiler
// Type: DQ9_Cheat.GameData.QuestDataList
// Assembly: DQ9_Cheat, Version=0.7.0.57, Culture=neutral, PublicKeyToken=null
// MVID: 9E5BE672-CBE6-45FB-AC35-96531044560E
// Assembly location: C:\Users\yzsco\Downloads\dq9_save_editor_0.7\DQCheat.Patched.0.7.exe

#nullable disable
namespace DQ9_Cheat.GameData
{
  public static class QuestDataList
  {
    private static System.Collections.Generic.List<QuestElement> _list = new System.Collections.Generic.List<QuestElement>();

    static QuestDataList()
    {
      QuestDataList._list.Add(new QuestElement((byte) 1, (byte) 1, false, "One Good Turn"));
      QuestDataList._list.Add(new QuestElement((byte) 3, (byte) 2, false, "Pleased as Punch"));
      QuestDataList._list.Add(new QuestElement((byte) 4, (byte) 3, false, "We Like to Party"));
      QuestDataList._list.Add(new QuestElement((byte) 83, (byte) 4, false, "Pick Me Up a Panacea"));
      QuestDataList._list.Add(new QuestElement((byte) 6, (byte) 5, false, "Herb'list"));
      QuestDataList._list.Add(new QuestElement((byte) 7, (byte) 6, false, "Get Well Water"));
      QuestDataList._list.Add(new QuestElement((byte) 8, (byte) 7, false, "Curious Crevice"));
      QuestDataList._list.Add(new QuestElement((byte) 9, (byte) 8, false, "Don't Cry Over Spilt Ink"));
      QuestDataList._list.Add(new QuestElement((byte) 5, (byte) 9, false, "Labour of Love"));
      QuestDataList._list.Add(new QuestElement((byte) 10, (byte) 10, false, "Wings of Love"));
      QuestDataList._list.Add(new QuestElement((byte) 86, (byte) 11, false, "The Not-So-Great Escape"));
      QuestDataList._list.Add(new QuestElement((byte) 37, (byte) 12, false, "Putting on the Glitz"));
      QuestDataList._list.Add(new QuestElement((byte) 38, (byte) 13, false, "All Fired Up"));
      QuestDataList._list.Add(new QuestElement((byte) 39, (byte) 14, false, "Snug as a Thug"));
      QuestDataList._list.Add(new QuestElement((byte) 40, (byte) 15, false, "Collapsus's Call"));
      QuestDataList._list.Add(new QuestElement((byte) 47, (byte) 16, false, "Help Meowt Here!"));
      QuestDataList._list.Add(new QuestElement((byte) 80, (byte) 17, false, "You Shouldn't Have...Really"));
      QuestDataList._list.Add(new QuestElement((byte) 81, (byte) 18, false, "Our Precious Precious"));
      QuestDataList._list.Add(new QuestElement((byte) 84, (byte) 19, false, "Moving House"));
      QuestDataList._list.Add(new QuestElement((byte) 88, (byte) 20, false, "A Masky Task"));
      QuestDataList._list.Add(new QuestElement((byte) 89, (byte) 21, false, "Spud-She-Like"));
      QuestDataList._list.Add(new QuestElement((byte) 90, (byte) 22, false, "Mantle à La Mode"));
      QuestDataList._list.Add(new QuestElement((byte) 85, (byte) 23, false, "Research Assistant"));
      QuestDataList._list.Add(new QuestElement((byte) 11, (byte) 24, false, "Battering Betterflies"));
      QuestDataList._list.Add(new QuestElement((byte) 82, (byte) 25, false, "Warbling Wellard"));
      QuestDataList._list.Add(new QuestElement((byte) 12, (byte) 26, false, "Doug and the Sluggers"));
      QuestDataList._list.Add(new QuestElement((byte) 87, (byte) 27, false, "Big-Headed Bard"));
      QuestDataList._list.Add(new QuestElement((byte) 45, (byte) 28, false, "Desert Foxes"));
      QuestDataList._list.Add(new QuestElement((byte) 42, (byte) 29, false, "Fool's Gold"));
      QuestDataList._list.Add(new QuestElement((byte) 43, (byte) 30, false, "Wrapper's Delight"));
      QuestDataList._list.Add(new QuestElement((byte) 44, (byte) 31, false, "Feathers for a Fan"));
      QuestDataList._list.Add(new QuestElement((byte) 107, (byte) 32, false, "Oil Get It!"));
      QuestDataList._list.Add(new QuestElement((byte) 41, (byte) 33, false, "Lady of the Dance"));
      QuestDataList._list.Add(new QuestElement((byte) 49, (byte) 34, false, "A Simple Task"));
      QuestDataList._list.Add(new QuestElement((byte) 110, (byte) 35, false, "All Dolled Up"));
      QuestDataList._list.Add(new QuestElement((byte) 50, (byte) 36, false, "Little Miss Bossy Boots"));
      QuestDataList._list.Add(new QuestElement((byte) 48, (byte) 37, false, "Funghi for a Fun Guy"));
      QuestDataList._list.Add(new QuestElement((byte) 79, (byte) 38, false, "Muffled Admiration"));
      QuestDataList._list.Add(new QuestElement((byte) 201, (byte) 39, false, "Follow That Fish!"));
      QuestDataList._list.Add(new QuestElement((byte) 91, (byte) 40, false, "Man Eating Vegetables"));
      QuestDataList._list.Add(new QuestElement((byte) 92, (byte) 41, false, "Style Gooru"));
      QuestDataList._list.Add(new QuestElement((byte) 94, (byte) 42, false, "Letter Getter"));
      QuestDataList._list.Add(new QuestElement((byte) 96, (byte) 43, false, "Maid to Wait"));
      QuestDataList._list.Add(new QuestElement((byte) 99, (byte) 44, false, "A Climber for a Climber"));
      QuestDataList._list.Add(new QuestElement((byte) 100, (byte) 45, false, "Tale of the Paper Trail"));
      QuestDataList._list.Add(new QuestElement((byte) 200, (byte) 46, false, "Puttin' 'Em In Platinum"));
      QuestDataList._list.Add(new QuestElement((byte) 103, (byte) 47, false, "Dozy Mayor"));
      QuestDataList._list.Add(new QuestElement((byte) 104, (byte) 48, false, "A Task for a Cask"));
      QuestDataList._list.Add(new QuestElement((byte) 105, (byte) 49, false, "Rock On!"));
      QuestDataList._list.Add(new QuestElement((byte) 109, (byte) 50, false, "Confession of Cin's"));
      QuestDataList._list.Add(new QuestElement((byte) 108, (byte) 51, false, "A Martyr to His Ma"));
      QuestDataList._list.Add(new QuestElement((byte) 106, (byte) 52, false, "Tall Order Cook"));
      QuestDataList._list.Add(new QuestElement((byte) 111, (byte) 53, false, "Magmalice Mania"));
      QuestDataList._list.Add(new QuestElement((byte) 112, (byte) 54, false, "Moai Memorabilia"));
      QuestDataList._list.Add(new QuestElement((byte) 113, (byte) 55, false, "Mummy's Little Hero"));
      QuestDataList._list.Add(new QuestElement((byte) 114, (byte) 56, false, "Nicholas's Necklace"));
      QuestDataList._list.Add(new QuestElement((byte) 115, (byte) 57, false, "Not Nicholas's Necklace"));
      QuestDataList._list.Add(new QuestElement((byte) 116, (byte) 58, false, "Fixing the Sicklops"));
      QuestDataList._list.Add(new QuestElement((byte) 118, (byte) 59, false, "Runny Bunny"));
      QuestDataList._list.Add(new QuestElement((byte) 119, (byte) 60, false, "That Makes Scents"));
      QuestDataList._list.Add(new QuestElement((byte) 120, (byte) 61, false, "Mager Migraine"));
      QuestDataList._list.Add(new QuestElement((byte) 117, (byte) 62, false, "Brian's Dyin' Wish"));
      QuestDataList._list.Add(new QuestElement((byte) 51, (byte) 63, false, "Keep Your Eyes Peeled"));
      QuestDataList._list.Add(new QuestElement((byte) 65, (byte) 64, false, "Turn in Your Badges"));
      QuestDataList._list.Add(new QuestElement((byte) 52, (byte) 65, false, "Operation Mercury"));
      QuestDataList._list.Add(new QuestElement((byte) 66, (byte) 66, false, "Operation Multithrust"));
      QuestDataList._list.Add(new QuestElement((byte) 53, (byte) 67, false, "Nab the Knife-Nicker"));
      QuestDataList._list.Add(new QuestElement((byte) 67, (byte) 68, false, "Spice Up Your Knife"));
      QuestDataList._list.Add(new QuestElement((byte) 54, (byte) 69, false, "You Scratch My Back..."));
      QuestDataList._list.Add(new QuestElement((byte) 68, (byte) 70, false, "Look, Back in Anger"));
      QuestDataList._list.Add(new QuestElement((byte) 56, (byte) 71, false, "Staunch the Stench"));
      QuestDataList._list.Add(new QuestElement((byte) 70, (byte) 72, false, "Jump for Joy"));
      QuestDataList._list.Add(new QuestElement((byte) 55, (byte) 73, false, "Whipping Boy's Wish"));
      QuestDataList._list.Add(new QuestElement((byte) 69, (byte) 74, false, "Mr Whippy's Wish"));
      QuestDataList._list.Add(new QuestElement((byte) 57, (byte) 75, false, "Rake a Tail Feather"));
      QuestDataList._list.Add(new QuestElement((byte) 71, (byte) 76, false, "Talonted Trio"));
      QuestDataList._list.Add(new QuestElement((byte) 58, (byte) 77, false, "Cool-Fanned Kook"));
      QuestDataList._list.Add(new QuestElement((byte) 72, (byte) 78, false, "Oh, the Indignity"));
      QuestDataList._list.Add(new QuestElement((byte) 61, (byte) 79, false, "Bring Oi Back Me Axe"));
      QuestDataList._list.Add(new QuestElement((byte) 75, (byte) 80, false, "'Atchet Job"));
      QuestDataList._list.Add(new QuestElement((byte) 62, (byte) 81, false, "Mallet's Mallet"));
      QuestDataList._list.Add(new QuestElement((byte) 76, (byte) 82, false, "To Shell and Back"));
      QuestDataList._list.Add(new QuestElement((byte) 64, (byte) 83, false, "Beautiful Bowginnings"));
      QuestDataList._list.Add(new QuestElement((byte) 78, (byte) 84, false, "Beauty and Beyond"));
      QuestDataList._list.Add(new QuestElement((byte) 63, (byte) 85, false, "Comeback Kid"));
      QuestDataList._list.Add(new QuestElement((byte) 77, (byte) 86, false, "Brave the Caves"));
      QuestDataList._list.Add(new QuestElement((byte) 59, (byte) 87, false, "Sucking Up to Buckler"));
      QuestDataList._list.Add(new QuestElement((byte) 73, (byte) 88, false, "Buckler's Buckler"));
      QuestDataList._list.Add(new QuestElement((byte) 60, (byte) 89, false, "Way of the Fitht"));
      QuestDataList._list.Add(new QuestElement((byte) 74, (byte) 90, false, "One Latht Tetht"));
      QuestDataList._list.Add(new QuestElement((byte) 14, (byte) 91, false, "Critical Appraisal"));
      QuestDataList._list.Add(new QuestElement((byte) 20, (byte) 92, false, "Warriors Three"));
      QuestDataList._list.Add(new QuestElement((byte) 15, (byte) 93, false, "Eggclesiastics"));
      QuestDataList._list.Add(new QuestElement((byte) 21, (byte) 94, false, "Nurtural Selection"));
      QuestDataList._list.Add(new QuestElement((byte) 16, (byte) 95, false, "Free the Faerie Two"));
      QuestDataList._list.Add(new QuestElement((byte) 22, (byte) 96, false, "Faerie Nearly There"));
      QuestDataList._list.Add(new QuestElement((byte) 17, (byte) 97, false, "Cry Wolf"));
      QuestDataList._list.Add(new QuestElement((byte) 23, (byte) 98, false, "Slowly, Slowly, Critty Golem"));
      QuestDataList._list.Add(new QuestElement((byte) 18, (byte) 99, false, "B-Coming One of the B-Team"));
      QuestDataList._list.Add(new QuestElement((byte) 24, (byte) 100, false, "Busted"));
      QuestDataList._list.Add(new QuestElement((byte) 13, (byte) 101, false, "Eggstreme Sports"));
      QuestDataList._list.Add(new QuestElement((byte) 19, (byte) 102, false, "Prat's the Way to Do It!"));
      QuestDataList._list.Add(new QuestElement((byte) 25, (byte) 103, false, "Gladiator Graduator"));
      QuestDataList._list.Add(new QuestElement((byte) 29, (byte) 104, false, "Glad to be of Service"));
      QuestDataList._list.Add(new QuestElement((byte) 33, (byte) 105, false, "Challengus Maximus"));
      QuestDataList._list.Add(new QuestElement((byte) 26, (byte) 106, false, "Taking Soul Control"));
      QuestDataList._list.Add(new QuestElement((byte) 30, (byte) 107, false, "Off the Record"));
      QuestDataList._list.Add(new QuestElement((byte) 34, (byte) 108, false, "Top-Flight Knight Fight"));
      QuestDataList._list.Add(new QuestElement((byte) 27, (byte) 109, false, "Elementary Training"));
      QuestDataList._list.Add(new QuestElement((byte) 31, (byte) 110, false, "Fource In the Field"));
      QuestDataList._list.Add(new QuestElement((byte) 35, (byte) 111, false, "The Fource...Forever"));
      QuestDataList._list.Add(new QuestElement((byte) 28, (byte) 112, false, "Ranger Changer"));
      QuestDataList._list.Add(new QuestElement((byte) 32, (byte) 113, false, "Hoarse Whisperer"));
      QuestDataList._list.Add(new QuestElement((byte) 36, (byte) 114, false, "One-Turn Wonder"));
      QuestDataList._list.Add(new QuestElement((byte) 124, (byte) 115, false, "Sages in the Pages"));
      QuestDataList._list.Add(new QuestElement((byte) 125, (byte) 116, false, "Sagier and Pagier"));
      QuestDataList._list.Add(new QuestElement((byte) 126, (byte) 117, false, "Engaging the Sage"));
      QuestDataList._list.Add(new QuestElement((byte) 128, (byte) 118, false, "A Star is Born"));
      QuestDataList._list.Add(new QuestElement((byte) 129, (byte) 119, false, "Sign for Your Supper"));
      QuestDataList._list.Add(new QuestElement((byte) 130, (byte) 120, false, "Your Time to Shine"));
      QuestDataList._list.Add(new QuestElement((byte) 133, (byte) 121, true, "A Cloudless Skye"));
      QuestDataList._list.Add(new QuestElement((byte) 134, (byte) 122, true, "Bert's Berfday"));
      QuestDataList._list.Add(new QuestElement((byte) 174, (byte) 123, true, "A Present from the Past"));
      QuestDataList._list.Add(new QuestElement((byte) 145, (byte) 124, true, "Risqué Respects"));
      QuestDataList._list.Add(new QuestElement((byte) 175, (byte) 125, true, "Perk Up, Patty!"));
      QuestDataList._list.Add(new QuestElement((byte) 2, (byte) 126, true, "Puff-Puff Performance"));
      QuestDataList._list.Add(new QuestElement((byte) 176, (byte) 127, true, "A Right Royal Nightmare"));
      QuestDataList._list.Add(new QuestElement((byte) 177, (byte) 128, true, "P-P-Pick Up A Pickaxe"));
      QuestDataList._list.Add(new QuestElement((byte) 178, (byte) 129, true, "A Spot of Book-Keyping"));
      QuestDataList._list.Add(new QuestElement((byte) 149, (byte) 130, true, "Exhume the Heirloom"));
      QuestDataList._list.Add(new QuestElement((byte) 179, (byte) 131, true, "Making Room in Brigadoom"));
      QuestDataList._list.Add(new QuestElement((byte) 135, (byte) 132, true, "Tree-Hugging Titan"));
      QuestDataList._list.Add(new QuestElement((byte) 180, (byte) 133, true, "Recruitment Drive"));
      QuestDataList._list.Add(new QuestElement((byte) 137, (byte) 134, true, "When Tax Attacks"));
      QuestDataList._list.Add(new QuestElement((byte) 181, (byte) 135, true, "To Brigadoom!"));
      QuestDataList._list.Add(new QuestElement((byte) 138, (byte) 136, true, "EXTERMINATE!"));
      QuestDataList._list.Add(new QuestElement((byte) 182, (byte) 137, true, "Yore for it Now!"));
      QuestDataList._list.Add(new QuestElement((byte) 155, (byte) 138, true, "Shaman You!"));
      QuestDataList._list.Add(new QuestElement((byte) 183, (byte) 139, true, "Has Sellma Sold Out?"));
      QuestDataList._list.Add(new QuestElement((byte) 164, (byte) 140, true, "Apt Pupil"));
      QuestDataList._list.Add(new QuestElement((byte) 184, (byte) 141, true, "Coffinwell Conundrum"));
      QuestDataList._list.Add(new QuestElement((byte) 127, (byte) 142, true, "Prayermongering"));
      QuestDataList._list.Add(new QuestElement((byte) 185, (byte) 143, true, "Thingy, King of, er..."));
      QuestDataList._list.Add(new QuestElement((byte) 158, (byte) 144, true, "Claws for Thought"));
      QuestDataList._list.Add(new QuestElement((byte) 186, (byte) 145, true, "Mysterious Monarch"));
      QuestDataList._list.Add(new QuestElement((byte) 202, (byte) 146, true, "Hail to the Queen"));
      QuestDataList._list.Add(new QuestElement((byte) 188, (byte) 147, true, "Licensed to Drive"));
      QuestDataList._list.Add(new QuestElement((byte) 189, (byte) 148, true, "Flaptricide"));
      QuestDataList._list.Add(new QuestElement((byte) 190, (byte) 149, true, "Intreeguing Mystery"));
      QuestDataList._list.Add(new QuestElement((byte) 191, (byte) 150, true, "Annihilimobliteration!?"));
      QuestDataList._list.Add(new QuestElement((byte) 143, (byte) 151, true, "Pushy Peddler"));
      QuestDataList._list.Add(new QuestElement((byte) 123, (byte) 152, true, "Marey Questmas"));
      QuestDataList._list.Add(new QuestElement((byte) 161, (byte) 153, true, "Not-So-Jolly Roger"));
      QuestDataList._list.Add(new QuestElement((byte) 156, (byte) 154, true, "Nightmarey Questmas"));
      QuestDataList._list.Add(new QuestElement((byte) 165, (byte) 155, true, "Christinamas Cake"));
      QuestDataList._list.Add(new QuestElement((byte) 192, (byte) 156, true, "Inn Search of an Inny"));
      QuestDataList._list.Add(new QuestElement((byte) 193, (byte) 157, true, "Inn for a Penny, Inn for an Inny"));
      QuestDataList._list.Add(new QuestElement((byte) 154, (byte) 158, true, "Battle Buff"));
      QuestDataList._list.Add(new QuestElement((byte) 194, (byte) 159, true, "Have You Seen Charlene?"));
      QuestDataList._list.Add(new QuestElement((byte) 195, (byte) 160, true, "Chronic Delay"));
      QuestDataList._list.Add(new QuestElement((byte) 196, (byte) 161, true, "Here With Nod's Tear"));
      QuestDataList._list.Add(new QuestElement((byte) 197, (byte) 162, true, "Do Nod Disturb"));
      QuestDataList._list.Add(new QuestElement((byte) 198, (byte) 163, true, "When a Star Wishes Upon You"));
      QuestDataList._list.Add(new QuestElement((byte) 148, (byte) 164, true, "Fixing Fickser's Fix"));
      QuestDataList._list.Add(new QuestElement((byte) 152, (byte) 165, true, "Shame on Goo"));
      QuestDataList._list.Add(new QuestElement((byte) 150, (byte) 166, true, "Research and Destroy"));
      QuestDataList._list.Add(new QuestElement((byte) 146, (byte) 167, true, "Who's a Pretty Boy?"));
      QuestDataList._list.Add(new QuestElement((byte) 157, (byte) 168, true, "Potty About Pots"));
      QuestDataList._list.Add(new QuestElement((byte) 153, (byte) 169, true, "Competition Commission"));
      QuestDataList._list.Add(new QuestElement((byte) 162, (byte) 170, true, "Maiding and Abetting"));
      QuestDataList._list.Add(new QuestElement((byte) 122, (byte) 171, true, "I Would Do Anyfang for Love"));
      QuestDataList._list.Add(new QuestElement((byte) 160, (byte) 172, true, "Namesake Maker"));
      QuestDataList._list.Add(new QuestElement((byte) 131, (byte) 173, true, "Plum Duffer"));
      QuestDataList._list.Add(new QuestElement((byte) 151, (byte) 174, true, "Agates Ain't Great...Are They?"));
      QuestDataList._list.Add(new QuestElement((byte) 168, (byte) 175, true, "If I 'Ad an 'Ammer"));
      QuestDataList._list.Add(new QuestElement((byte) 139, (byte) 176, true, "Well Forgetful"));
      QuestDataList._list.Add(new QuestElement((byte) 166, (byte) 177, true, "Tones of the Bones"));
      QuestDataList._list.Add(new QuestElement((byte) 173, (byte) 178, true, "From Rust to Riches"));
      QuestDataList._list.Add(new QuestElement((byte) 140, (byte) 179, true, "Pants Macabre"));
      QuestDataList._list.Add(new QuestElement((byte) 169, (byte) 180, true, "Wrecking Wrecks"));
      QuestDataList._list.Add(new QuestElement((byte) 170, (byte) 181, true, "Can We Borya for a Second?"));
      QuestDataList._list.Add(new QuestElement((byte) 159, (byte) 182, true, "An Immaculate Conception"));
      QuestDataList._list.Add(new QuestElement((byte) 132, (byte) 183, true, "Poison Needle 1 Ow 1"));
      QuestDataList._list.Add(new QuestElement((byte) 136, (byte) 184, true, "Bleats Me"));
    }

    public static System.Collections.Generic.List<QuestElement> List => QuestDataList._list;
  }
}
