// Decompiled with JetBrains decompiler
// Type: DQ9_Cheat.GameData.QuestDataList
// Assembly: DQ9_Cheat, Version=0.7.0.57, Culture=neutral, PublicKeyToken=null
// MVID: 9E5BE672-CBE6-45FB-AC35-96531044560E
// Assembly location: dq9_save_editor_0.7\DQCheat.Patched.0.7.exe

using System.Collections.Generic;

namespace DQ9_Cheat.GameData
{
  public static class QuestDataList
  {
    private static List<QuestElement> _list = new List<QuestElement>();

    static QuestDataList()
    {
      _list.Add(new QuestElement(1, 1, false, "One Good Turn"));
      _list.Add(new QuestElement(3, 2, false, "Pleased as Punch"));
      _list.Add(new QuestElement(4, 3, false, "We Like to Party"));
      _list.Add(new QuestElement(83, 4, false, "Pick Me Up a Panacea"));
      _list.Add(new QuestElement(6, 5, false, "Herb'list"));
      _list.Add(new QuestElement(7, 6, false, "Get Well Water"));
      _list.Add(new QuestElement(8, 7, false, "Curious Crevice"));
      _list.Add(new QuestElement(9, 8, false, "Don't Cry Over Spilt Ink"));
      _list.Add(new QuestElement(5, 9, false, "Labour of Love"));
      _list.Add(new QuestElement(10, 10, false, "Wings of Love"));
      _list.Add(new QuestElement(86, 11, false, "The Not-So-Great Escape"));
      _list.Add(new QuestElement(37, 12, false, "Putting on the Glitz"));
      _list.Add(new QuestElement(38, 13, false, "All Fired Up"));
      _list.Add(new QuestElement(39, 14, false, "Snug as a Thug"));
      _list.Add(new QuestElement(40, 15, false, "Collapsus's Call"));
      _list.Add(new QuestElement(47, 16, false, "Help Meowt Here!"));
      _list.Add(new QuestElement(80, 17, false, "You Shouldn't Have...Really"));
      _list.Add(new QuestElement(81, 18, false, "Our Precious Precious"));
      _list.Add(new QuestElement(84, 19, false, "Moving House"));
      _list.Add(new QuestElement(88, 20, false, "A Masky Task"));
      _list.Add(new QuestElement(89, 21, false, "Spud-She-Like"));
      _list.Add(new QuestElement(90, 22, false, "Mantle à La Mode"));
      _list.Add(new QuestElement(85, 23, false, "Research Assistant"));
      _list.Add(new QuestElement(11, 24, false, "Battering Betterflies"));
      _list.Add(new QuestElement(82, 25, false, "Warbling Wellard"));
      _list.Add(new QuestElement(12, 26, false, "Doug and the Sluggers"));
      _list.Add(new QuestElement(87, 27, false, "Big-Headed Bard"));
      _list.Add(new QuestElement(45, 28, false, "Desert Foxes"));
      _list.Add(new QuestElement(42, 29, false, "Fool's Gold"));
      _list.Add(new QuestElement(43, 30, false, "Wrapper's Delight"));
      _list.Add(new QuestElement(44, 31, false, "Feathers for a Fan"));
      _list.Add(new QuestElement(107, 32, false, "Oil Get It!"));
      _list.Add(new QuestElement(41, 33, false, "Lady of the Dance"));
      _list.Add(new QuestElement(49, 34, false, "A Simple Task"));
      _list.Add(new QuestElement(110, 35, false, "All Dolled Up"));
      _list.Add(new QuestElement(50, 36, false, "Little Miss Bossy Boots"));
      _list.Add(new QuestElement(48, 37, false, "Funghi for a Fun Guy"));
      _list.Add(new QuestElement(79, 38, false, "Muffled Admiration"));
      _list.Add(new QuestElement(201, 39, false, "Follow That Fish!"));
      _list.Add(new QuestElement(91, 40, false, "Man Eating Vegetables"));
      _list.Add(new QuestElement(92, 41, false, "Style Gooru"));
      _list.Add(new QuestElement(94, 42, false, "Letter Getter"));
      _list.Add(new QuestElement(96, 43, false, "Maid to Wait"));
      _list.Add(new QuestElement(99, 44, false, "A Climber for a Climber"));
      _list.Add(new QuestElement(100, 45, false, "Tale of the Paper Trail"));
      _list.Add(new QuestElement(200, 46, false, "Puttin' 'Em In Platinum"));
      _list.Add(new QuestElement(103, 47, false, "Dozy Mayor"));
      _list.Add(new QuestElement(104, 48, false, "A Task for a Cask"));
      _list.Add(new QuestElement(105, 49, false, "Rock On!"));
      _list.Add(new QuestElement(109, 50, false, "Confession of Cin's"));
      _list.Add(new QuestElement(108, 51, false, "A Martyr to His Ma"));
      _list.Add(new QuestElement(106, 52, false, "Tall Order Cook"));
      _list.Add(new QuestElement(111, 53, false, "Magmalice Mania"));
      _list.Add(new QuestElement(112, 54, false, "Moai Memorabilia"));
      _list.Add(new QuestElement(113, 55, false, "Mummy's Little Hero"));
      _list.Add(new QuestElement(114, 56, false, "Nicholas's Necklace"));
      _list.Add(new QuestElement(115, 57, false, "Not Nicholas's Necklace"));
      _list.Add(new QuestElement(116, 58, false, "Fixing the Sicklops"));
      _list.Add(new QuestElement(118, 59, false, "Runny Bunny"));
      _list.Add(new QuestElement(119, 60, false, "That Makes Scents"));
      _list.Add(new QuestElement(120, 61, false, "Mager Migraine"));
      _list.Add(new QuestElement(117, 62, false, "Brian's Dyin' Wish"));
      _list.Add(new QuestElement(51, 63, false, "Keep Your Eyes Peeled"));
      _list.Add(new QuestElement(65, 64, false, "Turn in Your Badges"));
      _list.Add(new QuestElement(52, 65, false, "Operation Mercury"));
      _list.Add(new QuestElement(66, 66, false, "Operation Multithrust"));
      _list.Add(new QuestElement(53, 67, false, "Nab the Knife-Nicker"));
      _list.Add(new QuestElement(67, 68, false, "Spice Up Your Knife"));
      _list.Add(new QuestElement(54, 69, false, "You Scratch My Back..."));
      _list.Add(new QuestElement(68, 70, false, "Look, Back in Anger"));
      _list.Add(new QuestElement(56, 71, false, "Staunch the Stench"));
      _list.Add(new QuestElement(70, 72, false, "Jump for Joy"));
      _list.Add(new QuestElement(55, 73, false, "Whipping Boy's Wish"));
      _list.Add(new QuestElement(69, 74, false, "Mr Whippy's Wish"));
      _list.Add(new QuestElement(57, 75, false, "Rake a Tail Feather"));
      _list.Add(new QuestElement(71, 76, false, "Talonted Trio"));
      _list.Add(new QuestElement(58, 77, false, "Cool-Fanned Kook"));
      _list.Add(new QuestElement(72, 78, false, "Oh, the Indignity"));
      _list.Add(new QuestElement(61, 79, false, "Bring Oi Back Me Axe"));
      _list.Add(new QuestElement(75, 80, false, "'Atchet Job"));
      _list.Add(new QuestElement(62, 81, false, "Mallet's Mallet"));
      _list.Add(new QuestElement(76, 82, false, "To Shell and Back"));
      _list.Add(new QuestElement(64, 83, false, "Beautiful Bowginnings"));
      _list.Add(new QuestElement(78, 84, false, "Beauty and Beyond"));
      _list.Add(new QuestElement(63, 85, false, "Comeback Kid"));
      _list.Add(new QuestElement(77, 86, false, "Brave the Caves"));
      _list.Add(new QuestElement(59, 87, false, "Sucking Up to Buckler"));
      _list.Add(new QuestElement(73, 88, false, "Buckler's Buckler"));
      _list.Add(new QuestElement(60, 89, false, "Way of the Fitht"));
      _list.Add(new QuestElement(74, 90, false, "One Latht Tetht"));
      _list.Add(new QuestElement(14, 91, false, "Critical Appraisal"));
      _list.Add(new QuestElement(20, 92, false, "Warriors Three"));
      _list.Add(new QuestElement(15, 93, false, "Eggclesiastics"));
      _list.Add(new QuestElement(21, 94, false, "Nurtural Selection"));
      _list.Add(new QuestElement(16, 95, false, "Free the Faerie Two"));
      _list.Add(new QuestElement(22, 96, false, "Faerie Nearly There"));
      _list.Add(new QuestElement(17, 97, false, "Cry Wolf"));
      _list.Add(new QuestElement(23, 98, false, "Slowly, Slowly, Critty Golem"));
      _list.Add(new QuestElement(18, 99, false, "B-Coming One of the B-Team"));
      _list.Add(new QuestElement(24, 100, false, "Busted"));
      _list.Add(new QuestElement(13, 101, false, "Eggstreme Sports"));
      _list.Add(new QuestElement(19, 102, false, "Prat's the Way to Do It!"));
      _list.Add(new QuestElement(25, 103, false, "Gladiator Graduator"));
      _list.Add(new QuestElement(29, 104, false, "Glad to be of Service"));
      _list.Add(new QuestElement(33, 105, false, "Challengus Maximus"));
      _list.Add(new QuestElement(26, 106, false, "Taking Soul Control"));
      _list.Add(new QuestElement(30, 107, false, "Off the Record"));
      _list.Add(new QuestElement(34, 108, false, "Top-Flight Knight Fight"));
      _list.Add(new QuestElement(27, 109, false, "Elementary Training"));
      _list.Add(new QuestElement(31, 110, false, "Fource In the Field"));
      _list.Add(new QuestElement(35, 111, false, "The Fource...Forever"));
      _list.Add(new QuestElement(28, 112, false, "Ranger Changer"));
      _list.Add(new QuestElement(32, 113, false, "Hoarse Whisperer"));
      _list.Add(new QuestElement(36, 114, false, "One-Turn Wonder"));
      _list.Add(new QuestElement(124, 115, false, "Sages in the Pages"));
      _list.Add(new QuestElement(125, 116, false, "Sagier and Pagier"));
      _list.Add(new QuestElement(126, 117, false, "Engaging the Sage"));
      _list.Add(new QuestElement(128, 118, false, "A Star is Born"));
      _list.Add(new QuestElement(129, 119, false, "Sign for Your Supper"));
      _list.Add(new QuestElement(130, 120, false, "Your Time to Shine"));
      _list.Add(new QuestElement(133, 121, true, "A Cloudless Skye"));
      _list.Add(new QuestElement(134, 122, true, "Bert's Berfday"));
      _list.Add(new QuestElement(174, 123, true, "A Present from the Past"));
      _list.Add(new QuestElement(145, 124, true, "Risqué Respects"));
      _list.Add(new QuestElement(175, 125, true, "Perk Up, Patty!"));
      _list.Add(new QuestElement(2, 126, true, "Puff-Puff Performance"));
      _list.Add(new QuestElement(176, 127, true, "A Right Royal Nightmare"));
      _list.Add(new QuestElement(177, 128, true, "P-P-Pick Up A Pickaxe"));
      _list.Add(new QuestElement(178, 129, true, "A Spot of Book-Keyping"));
      _list.Add(new QuestElement(149, 130, true, "Exhume the Heirloom"));
      _list.Add(new QuestElement(179, 131, true, "Making Room in Brigadoom"));
      _list.Add(new QuestElement(135, 132, true, "Tree-Hugging Titan"));
      _list.Add(new QuestElement(180, 133, true, "Recruitment Drive"));
      _list.Add(new QuestElement(137, 134, true, "When Tax Attacks"));
      _list.Add(new QuestElement(181, 135, true, "To Brigadoom!"));
      _list.Add(new QuestElement(138, 136, true, "EXTERMINATE!"));
      _list.Add(new QuestElement(182, 137, true, "Yore for it Now!"));
      _list.Add(new QuestElement(155, 138, true, "Shaman You!"));
      _list.Add(new QuestElement(183, 139, true, "Has Sellma Sold Out?"));
      _list.Add(new QuestElement(164, 140, true, "Apt Pupil"));
      _list.Add(new QuestElement(184, 141, true, "Coffinwell Conundrum"));
      _list.Add(new QuestElement(127, 142, true, "Prayermongering"));
      _list.Add(new QuestElement(185, 143, true, "Thingy, King of, er..."));
      _list.Add(new QuestElement(158, 144, true, "Claws for Thought"));
      _list.Add(new QuestElement(186, 145, true, "Mysterious Monarch"));
      _list.Add(new QuestElement(202, 146, true, "Hail to the Queen"));
      _list.Add(new QuestElement(188, 147, true, "Licensed to Drive"));
      _list.Add(new QuestElement(189, 148, true, "Flaptricide"));
      _list.Add(new QuestElement(190, 149, true, "Intreeguing Mystery"));
      _list.Add(new QuestElement(191, 150, true, "Annihilimobliteration!?"));
      _list.Add(new QuestElement(143, 151, true, "Pushy Peddler"));
      _list.Add(new QuestElement(123, 152, true, "Marey Questmas"));
      _list.Add(new QuestElement(161, 153, true, "Not-So-Jolly Roger"));
      _list.Add(new QuestElement(156, 154, true, "Nightmarey Questmas"));
      _list.Add(new QuestElement(165, 155, true, "Christinamas Cake"));
      _list.Add(new QuestElement(192, 156, true, "Inn Search of an Inny"));
      _list.Add(new QuestElement(193, 157, true, "Inn for a Penny, Inn for an Inny"));
      _list.Add(new QuestElement(154, 158, true, "Battle Buff"));
      _list.Add(new QuestElement(194, 159, true, "Have You Seen Charlene?"));
      _list.Add(new QuestElement(195, 160, true, "Chronic Delay"));
      _list.Add(new QuestElement(196, 161, true, "Here With Nod's Tear"));
      _list.Add(new QuestElement(197, 162, true, "Do Nod Disturb"));
      _list.Add(new QuestElement(198, 163, true, "When a Star Wishes Upon You"));
      _list.Add(new QuestElement(148, 164, true, "Fixing Fickser's Fix"));
      _list.Add(new QuestElement(152, 165, true, "Shame on Goo"));
      _list.Add(new QuestElement(150, 166, true, "Research and Destroy"));
      _list.Add(new QuestElement(146, 167, true, "Who's a Pretty Boy?"));
      _list.Add(new QuestElement(157, 168, true, "Potty About Pots"));
      _list.Add(new QuestElement(153, 169, true, "Competition Commission"));
      _list.Add(new QuestElement(162, 170, true, "Maiding and Abetting"));
      _list.Add(new QuestElement(122, 171, true, "I Would Do Anyfang for Love"));
      _list.Add(new QuestElement(160, 172, true, "Namesake Maker"));
      _list.Add(new QuestElement(131, 173, true, "Plum Duffer"));
      _list.Add(new QuestElement(151, 174, true, "Agates Ain't Great...Are They?"));
      _list.Add(new QuestElement(168, 175, true, "If I 'Ad an 'Ammer"));
      _list.Add(new QuestElement(139, 176, true, "Well Forgetful"));
      _list.Add(new QuestElement(166, 177, true, "Tones of the Bones"));
      _list.Add(new QuestElement(173, 178, true, "From Rust to Riches"));
      _list.Add(new QuestElement(140, 179, true, "Pants Macabre"));
      _list.Add(new QuestElement(169, 180, true, "Wrecking Wrecks"));
      _list.Add(new QuestElement(170, 181, true, "Can We Borya for a Second?"));
      _list.Add(new QuestElement(159, 182, true, "An Immaculate Conception"));
      _list.Add(new QuestElement(132, 183, true, "Poison Needle 1 Ow 1"));
      _list.Add(new QuestElement(136, 184, true, "Bleats Me"));
    }

    public static List<QuestElement> List => _list;
  }
}
