// Decompiled with JetBrains decompiler
// Type: DQ9_Cheat.GameData.TitleDataList
// Assembly: DQ9_Cheat, Version=0.7.0.57, Culture=neutral, PublicKeyToken=null
// MVID: 9E5BE672-CBE6-45FB-AC35-96531044560E
// Assembly location: dq9_save_editor_0.7\DQCheat.Patched.0.7.exe

using System.Collections.Generic;
using System.Collections.ObjectModel;

namespace DQ9_Cheat.GameData;

internal static class TitleDataList
{
    public const int ClearTitleIndex = 425;
    private static readonly List<TitleElement> _list = new();

    static TitleDataList()
    {
        var strArray1 = new string[453]
        {
            "Celestial Sentinel",
            "Heralded Hero",
            "Superhero",
            "Heavenly Hero",
            "Legendary Hero",
            "Spelunker",
            "Spunky Spelunker",
            "Spelunking Specialist",
            "Supreme Spelunker",
            "Cave Dweller",
            "Cave Craver",
            "From Cradle to Cave",
            "Stalag Mighty",
            "Caving Lunatic",
            "Service Provider",
            "Helping Hand",
            "Selfless Soul",
            "Fairy Godfather",
            "Father Questmas",
            "Expressionist",
            "Commis Chef",
            "Chef de Partie",
            "Sous Chef",
            "Chef d'Alchimie",
            "Crème de la Crème",
            "Amateur Alchemist",
            "Enthusiastic Alchemist",
            "Avid Alchemist",
            "Alchemaniac",
            "Alcheholic",
            "Krak Pot Crackpot",
            null,
            null,
            "Seasoned Traveller",
            "Sightseer",
            "Wayfarer",
            "Globetrotter",
            "Wanderluster",
            "Constant Companion",
            "Firm Friend",
            "Best Buddy",
            "Oldest and Goldest",
            "Friend to the End",
            "Victor",
            "On-Fire Fighter",
            "Winning Streaker",
            "Win-a-Lot Prime",
            "Winvincible",
            "Name Dropper",
            "Glory Hunter",
            "Man of Many Names",
            "Titled Peer",
            "Titan of Titles",
            "Cold Caller",
            "Deal Closer",
            "Salesperson of the Week",
            "Top Seller",
            "Celestial Salesperson",
            "Huntsman",
            "Hunter Gatherer",
            "Top Tracker",
            "Head Hunter",
            "Big Game Hunter",
            "Itemiser",
            "King of Collectors",
            "Follower of Fashion",
            "Clothes Horse",
            "Trendspotter",
            "Trendsetter",
            "Fashionista",
            null,
            null,
            "Regular Churchgoer",
            "Coffin Dodger",
            "Dauntless Deadbeat",
            "White Sticker Saver",
            "Blue Sticker Saver",
            "Red Sticker Saver",
            "Silver Sticker Saver",
            "Gold Sticker Saver",
            null,
            null,
            null,
            "Herbalist",
            null,
            "Happy-Go-Lucky",
            "Birthday Boy",
            "Field Marshal",
            "Archdeacon",
            "Grand Wizard",
            "Grandmaster",
            "Bandit King",
            "Bard of High Regard",
            "Gladius Maximus",
            "Caster Blaster",
            "Knight Banneret",
            "Eco Warrior",
            "Mahatma",
            "Superstar",
            "Ceaseless Swordsman",
            "Perpetual Priest",
            "Steadfast Caster",
            "Born-Again Brawler",
            "Career Criminal",
            "Boundless Bard",
            "Undefeated Champion",
            "Endless Armamentalist",
            "Knight to Remember",
            "Constant Gardener",
            "Karma Karmeleon",
            "Limitless Luminary",
            "Laid-Back Lad",
            "Prince of Posers",
            "Ladykiller",
            "Cool Customer",
            "",
            "Simple Simon",
            "Distinguished Gentleman",
            "",
            "Swordsman",
            "Skilled Swordsman",
            "Fine Fencer",
            "Fab Fencer",
            "Cut 'n' Thruster",
            "Famed Fencer",
            "Blinding Blade",
            "Blistering Blade",
            "Sword Saint",
            "Lord of the Sword",
            "Lancer",
            "Practical Poker",
            "Advanced Lancer",
            "Sincere Spear",
            "Flash Lancer",
            "Lance-a-Lot",
            "Fierce Piercer",
            "Searing Spear",
            "Smokin' Poker",
            "Lord of the Lance",
            "Knifer",
            "Dagger Waggler",
            "Shiv Shover",
            "Swanky Shanker",
            "Struttin' Cutter",
            "Established Stabber",
            "Swaggering Daggerer",
            "Knife Knight",
            "Doyen of Daggers",
            "Know-It-All Knifer",
            "Shield Wielder",
            "Beater Blocker",
            "Body Guard",
            "Public Defender",
            "Hardy Guardian",
            "Managing Protector",
            "Executive Protector",
            "Magnetic Shield",
            "Stonewaller",
            "Guardian Force",
            "Courageous Kid",
            "Plucky Devil",
            "Bold Soul",
            "Brave Heart",
            "Intrepid Adventurer",
            "Stout-Hearted Sort",
            "Gallant Guy",
            "Valiant Combatant",
            "Valorous Vanquisher",
            "Peerlessly Fearless",
            "Boy Wander",
            "Wandsman",
            "Wand Waver",
            "Wand Ambition",
            "Fond of the Wand",
            "Weighty Wandsman",
            "Wild Blue Wander",
            "Wand From Beyond",
            "Wandering Star",
            "Wonder Wander",
            "Member of Staff",
            "Pole Soldier",
            "Polearmourer",
            "Staff Sergeant",
            "Baton Twirler",
            "Baton Batterer",
            "Staff-and-a-Half",
            "Stick-in-the-Head",
            "Pole Star",
            "Chief of Staff",
            "Believer",
            "Acolyte",
            "Mendicant",
            "Parish Priest",
            "Presbyter",
            "Abbot",
            "Bishop",
            "Archbishop",
            "Cardinal",
            "Saint",
            "Whipper-Snapper",
            "Lashing Lad",
            "Mr Whippy",
            "Flashing Lash",
            "Thong Thwacker",
            "Crackerjack",
            "Purging Scourge",
            "Whippopotamus",
            "Sir Lashalot",
            "Scourge of the Gods",
            "Mediocre Invoker",
            "Charm School Graduate",
            "Sort-Of Sorcerer",
            "Good Speller",
            "Abracadabrer",
            "Mentalist",
            "Whizzard",
            "Mager General",
            "Hard-Core Sorcerer",
            "Master Caster",
            "Surface Scratcher",
            "Talented Taloneer",
            "Nail Technician",
            "Nail Artist",
            "Soaring Claws",
            "Roaring Claws",
            "Claws of Gore",
            "Coffin Nailer",
            "Devil's Claw",
            "Scratchmaster",
            "Fair Fanner",
            "Fan Fancier",
            "Fancy Fan",
            "Fantasist",
            "Fan Belter",
            "Defander of the Realm",
            "Fandamentalist",
            "Diehard Fan",
            "Fan Atic",
            "Leviafan",
            "White Belt",
            "Yellow Belt",
            "Orange Belt",
            "Red Belt",
            "Green Belt",
            "Blue Belt",
            "Purple Belt",
            "Brown Belt",
            "Black Belt",
            "Tenth Dan",
            "Energiser",
            "Surpriser",
            "Chastiser",
            "Galvaniser",
            "Pressuriser",
            "Equaliser",
            "Agoniser",
            "Terroriser",
            "Pulveriser",
            "Atomiser",
            "Secret Seeker",
            "Gold Digger",
            "Booty Uprooter",
            "Trovehound",
            "Treasure Hunter",
            "Recoverer of Riches",
            "Cache Machine",
            "Bonanzer",
            "Hoard Lord",
            "Bullion Billionaire",
            "Smooth Mover",
            "Duck 'n' Diver",
            "Tumbler",
            "Gymnast",
            "Acrobat",
            "Aerialist",
            "Nimble Gnome",
            "Human Dynamo",
            "Fearless Flea",
            "Flying Wallenda",
            "Whittler",
            "Log Chopper",
            "Woodcutter",
            "Lumberjack",
            "Tree Surgeon",
            "Top of the Chops",
            "Copse Killer",
            "Groverazer",
            "Woodwrecker",
            "Deforester",
            "Nail Knocker",
            "Hammerhead",
            "Sledge Swinger",
            "Sound Pounder",
            "Heavy Hitter",
            "Hammer Slammer",
            "Impact Crusher",
            "Blunt-Force Traumatiser",
            "Atom Smasher",
            "Hammer of the Gods",
            "Bruiser",
            "Brawler",
            "Battler",
            "Challenger",
            "Winner",
            "Champion",
            "Vanquisher",
            "Conqueror",
            "Decimator",
            "Annihilator",
            "String Twanger",
            "Target Shooter",
            "Marksman",
            "Sharpshooter",
            "Deadeye",
            "Sniper",
            "Bow Diddly",
            "Arrow Artist",
            "Arch-Archer",
            "Sagittarean",
            "Pyro Private",
            "Corporeal Corporal",
            "Snow Sergeant",
            "Lofty Lieutenant",
            "Cloudburst Captain",
            "Magisterial Major",
            "Crepuscular Colonel",
            "Boreal Brigadier",
            "Geo General",
            "Star Marshal",
            "Slight Knight",
            "Alright Knight",
            "Polite Knight",
            "Light Knight",
            "Bright Knight",
            "White Knight",
            "Right Knight",
            "Upright Knight",
            "Outright Knight",
            "Out-of-Sight Knight",
            "Baby Boomer",
            "Comeback Kid",
            "Boomeranger",
            "Boomerangutan",
            "Fine Flinger",
            "Pukka Chucker",
            "Spin Bowler",
            "Throwstick Pro",
            "Whirling Dervish",
            "Sonic Boomeranger",
            "Optimist",
            "Romanticist",
            "Anthropologist",
            "Geologist",
            "Naturalist",
            "Occultist",
            "Illuminist",
            "Sophist",
            "Theologist",
            "Polymath",
            "Wannabe",
            "Bit Player",
            "Young Hopeful",
            "Rising Star",
            "Respected Artiste",
            "Cult Hero",
            "Mover and Shaker",
            "Big Shot",
            "Major Player",
            "Phenomenon",
            "Backpacker",
            "Happy Camper",
            "Outdoorsman",
            "Forest Dweller",
            "Wild Child",
            "Survivalist",
            "Bushcraftsman",
            "Talented Tracker",
            "Pathfinder",
            "King of the Jungle",
            "Heir of Heroes",
            "Majesty of Midenhall",
            "Future King of Cannock",
            "Moonbrooke Maiden",
            "Bonnie Burland Boy",
            "Tomboy Tsarevna",
            "Tutor of Tsarevna",
            "Most Holiest Priest",
            "Quare Feen",
            "Dramatic Dancer",
            "Foxy Fortune-Teller",
            "Best Friend Bride",
            "Well-Bred Bride",
            "Bossy Bride",
            "Punk-Haired Pugilist",
            "Elegant Oneiromancer",
            "Devil-May-Care Mage",
            "Reckless Royal",
            "Mayor's Heir",
            "Cursed King",
            "The Guv'nor",
            "Highly Strung Heiress",
            "Tasty Templar",
            "PASSION Personified",
            "Femme Fatale",
            "Bane of Baramos",
            "Chosen One",
            "Heavenly Groom",
            "Dream Warrior",
            "Estard's Finest",
            "Trodain Royal Guard",
            "Stella Artiste",
            "Stereotypical Sage",
            "Exemplary Luminary",
            "Textbook Trooper",
            "Prototypical Priest",
            "Model Minstrel",
            "Stock Stealer",
            "Fadiator",
            "Everyday Knight",
            "Paradigmatic Pugilist",
            "Average Armamentalist",
            "Classic Caster",
            "Regular Ranger",
            "Light-Speed Champion",
            "Hot to Trot",
            "Sleeper on the Job",
            "Easy Rider",
            "Exterminator",
            "Shopaholic",
            "Pacifist",
            "Socialite",
            "Philanthropist",
            "Cartographer",
            "Mighty Inviter",
            "Entitled Adventurer",
            "Completely Potty",
            "Zoologist",
            "Punchbag",
            "Snappy Dresser",
            "Recipe Researcher",
            null,
            "Moneybags",
            "Grievous Angel",
            "Monster Masher",
            "Fleet Completer",
            "Steady Eddie",
            "Party Hopper",
            "Immaculate Completion",
            "Guardian Angel",
            "Lionheart",
            "Sent From Above",
            "Watched-Over One",
            "Storied Saviour"
        };
        var strArray2 = new string[453]
        {
            "Celestial Sentinel",
            "Heralded Heroine",
            "Superheroine",
            "Heavenly Heroine",
            "Legendary Heroine",
            "Spelunker",
            "Spunky Spelunker",
            "Spelunking Specialist",
            "Supreme Spelunker",
            "Cave Dweller",
            "Cave Craver",
            "From Cradle to Cave",
            "Stalag Mighty",
            "Caving Lunatic",
            "Service Provider",
            "Helping Hand",
            "Selfless Soul",
            "Fairy Godmother",
            "Mother Questmas",
            "Expressionist",
            "Commis Chef",
            "Chef de Partie",
            "Sous Chef",
            "Chef d'Alchimie",
            "Crème de la Crème",
            "Amateur Alchemist",
            "Enthusiastic Alchemist",
            "Avid Alchemist",
            "Alchemaniac",
            "Alcheholic",
            "Krak Pot Crackpot",
            null,
            null,
            "Seasoned Traveller",
            "Sightseer",
            "Wayfarer",
            "Globetrotter",
            "Wanderluster",
            "Constant Companion",
            "Firm Friend",
            "Best Buddy",
            "Oldest and Goldest",
            "Friend to the End",
            "Victoria",
            "On-Fire Fighter",
            "Winning Streaker",
            "Win-a-Lot Prime",
            "Winvincible",
            "Name Dropper",
            "Glory Hunter",
            "Woman of Many Names",
            "Titled Peer",
            "Titan of Titles",
            "Cold Caller",
            "Deal Closer",
            "Salesperson of the Week",
            "Top Seller",
            "Celestial Salesperson",
            "Huntswoman",
            "Hunter Gatherer",
            "Top Tracker",
            "Head Hunter",
            "Big Game Hunter",
            "Itemiser",
            "Queen of Collectors",
            "Follower of Fashion",
            "Clothes Horse",
            "Trendspotter",
            "Trendsetter",
            "Fashionista",
            null,
            null,
            "Regular Churchgoer",
            "Coffin Dodger",
            "Dauntless Deadbeat",
            "White Sticker Saver",
            "Blue Sticker Saver",
            "Red Sticker Saver",
            "Silver Sticker Saver",
            "Gold Sticker Saver",
            null,
            null,
            null,
            "Herbalist",
            null,
            "Happy-Go-Lucky",
            "Birthday Girl",
            "Field Marshal",
            "Archdeacon",
            "Grand Wizard",
            "Grandmaster",
            "Bandit Queen",
            "Bard of High Regard",
            "Gladius Maximus",
            "Caster Blaster",
            "Knight Banneret",
            "Eco Warrior",
            "Mahatma",
            "Superstar",
            "Ceaseless Swordswoman",
            "Perpetual Priest",
            "Steadfast Caster",
            "Born-Again Brawler",
            "Career Criminal",
            "Boundless Bard",
            "Undefeated Champion",
            "Endless Armamentalist",
            "Knight to Remember",
            "Constant Gardener",
            "Karma Karmeleon",
            "Limitless Luminary",
            "Laid-Back Lady",
            "Princess of Posers",
            "Man Magnet",
            "",
            "Haughty Beauty",
            "Simple Simone",
            "",
            "Society Lady",
            "Swordswoman",
            "Skilled Swordswoman",
            "Fine Fencer",
            "Fab Fencer",
            "Cut 'n' Thruster",
            "Famed Fencer",
            "Blinding Blade",
            "Blistering Blade",
            "Sword Saint",
            "Sworderella",
            "Lancer",
            "Practical Poker",
            "Advanced Lancer",
            "Sincere Spear",
            "Flash Lancer",
            "Lance-a-Lot",
            "Fierce Piercer",
            "Searing Spear",
            "Smokin' Poker",
            "Lady of the Lance",
            "Knifer",
            "Dagger Waggler",
            "Shiv Shover",
            "Swanky Shanker",
            "Struttin' Cutter",
            "Established Stabber",
            "Swaggering Daggerer",
            "Knife Knight",
            "Doyenne of Daggers",
            "Know-It-All Knifer",
            "Shield Wielder",
            "Beater Blocker",
            "Body Guard",
            "Public Defender",
            "Hardy Guardian",
            "Managing Protector",
            "Executive Protector",
            "Magnetic Shield",
            "Stonewaller",
            "Guardian Force",
            "Courageous Kid",
            "Plucky Devil",
            "Bold Soul",
            "Brave Heart",
            "Intrepid Adventurer",
            "Stout-Hearted Sort",
            "Gallant Girl",
            "Valiant Combatant",
            "Valorous Vanquisher",
            "Peerlessly Fearless",
            "Girl Wander",
            "Wandswoman",
            "Wand Waver",
            "Wand Ambition",
            "Fond of the Wand",
            "Weighty Wandswoman",
            "Wild Blue Wander",
            "Wand From Beyond",
            "Wandering Star",
            "Wonder Wander",
            "Member of Staff",
            "Pole Soldier",
            "Polearmourer",
            "Staff Sergeant",
            "Baton Twirler",
            "Baton Batterer",
            "Staff-and-a-Half",
            "Stick-in-the-Head",
            "Pole Star",
            "Chief of Staff",
            "Believer",
            "Postulant",
            "Votary",
            "Nun of the Parish",
            "Missionary",
            "Abbess",
            "Prioress",
            "Mother Superior",
            "Beatificant",
            "Saint",
            "Whipper-Snapper",
            "Lashing Lass",
            "Mrs Whippy",
            "Flashing Lash",
            "Thong Thwacker",
            "Crackerjane",
            "Purging Scourge",
            "Whippopotamus",
            "Lady Lashalot",
            "Scourge of the Gods",
            "Mediocre Invoker",
            "Charm School Graduate",
            "Sort-Of Sorcerer",
            "Good Speller",
            "Abracadabrer",
            "Mentalist",
            "Wicked Witch",
            "Mager General",
            "Hard-Core Sorceress",
            "Master Caster",
            "Surface Scratcher",
            "Talented Taloneer",
            "Nail Technician",
            "Nail Artist",
            "Soaring Claws",
            "Roaring Claws",
            "Claws of Gore",
            "Coffin Nailer",
            "Devil's Claw",
            "Scratchmaster",
            "Fair Fanner",
            "Fan Fancier",
            "Fancy Fan",
            "Fantasist",
            "Fan Belter",
            "Defander of the Realm",
            "Fandamentalist",
            "Diehard Fan",
            "Fan Atic",
            "Leviafan",
            "White Belt",
            "Yellow Belt",
            "Orange Belt",
            "Red Belt",
            "Green Belt",
            "Blue Belt",
            "Purple Belt",
            "Brown Belt",
            "Black Belt",
            "Tenth Dan",
            "Energiser",
            "Surpriser",
            "Chastiser",
            "Galvaniser",
            "Pressuriser",
            "Equaliser",
            "Agoniser",
            "Terroriser",
            "Pulveriser",
            "Atomiser",
            "Secret Seeker",
            "Gold Digger",
            "Booty Uprooter",
            "Trovehound",
            "Treasure Hunter",
            "Recoverer of Riches",
            "Cache Machine",
            "Bonanzer",
            "Hoard Lord",
            "Bullion Billionaire",
            "Smooth Mover",
            "Duck 'n' Diver",
            "Tumbler",
            "Gymnast",
            "Acrobat",
            "Aerialist",
            "Nimble Nymph",
            "Human Dynamo",
            "Fearless Flea",
            "Flying Wallenda",
            "Whittler",
            "Log Chopper",
            "Woodcutter",
            "Lumberjill",
            "Tree Surgeon",
            "Top of the Chops",
            "Copse Killer",
            "Groverazer",
            "Woodwrecker",
            "Deforester",
            "Nail Knocker",
            "Hammerhead",
            "Sledge Swinger",
            "Sound Pounder",
            "Heavy Hitter",
            "Hammer Slammer",
            "Impact Crusher",
            "Blunt-Force Traumatiser",
            "Atom Smasher",
            "Hammer of the Gods",
            "Bruiser",
            "Brawler",
            "Battler",
            "Challenger",
            "Winner",
            "Champion",
            "Vanquisher",
            "Conqueror",
            "Decimator",
            "Annihilator",
            "String Twanger",
            "Target Shooter",
            "Markswoman",
            "Sharpshooter",
            "Deadeye",
            "Sniper",
            "Bow Diddly",
            "Arrow Artist",
            "Arch-Archer",
            "Sagittarean",
            "Pyro Private",
            "Corporeal Corporal",
            "Snow Sergeant",
            "Lofty Lieutenant",
            "Cloudburst Captain",
            "Magisterial Major",
            "Crepuscular Colonel",
            "Boreal Brigadier",
            "Geo General",
            "Star Marshal",
            "Slight Knight",
            "Alright Knight",
            "Polite Knight",
            "Light Knight",
            "Bright Knight",
            "White Knight",
            "Right Knight",
            "Upright Knight",
            "Outright Knight",
            "Out-of-Sight Knight",
            "Baby Boomer",
            "Comeback Kid",
            "Boomeranger",
            "Boomerangutan",
            "Fine Flinger",
            "Pukka Chucker",
            "Spin Bowler",
            "Throwstick Pro",
            "Whirling Dervish",
            "Sonic Boomeranger",
            "Optimist",
            "Romanticist",
            "Anthropologist",
            "Geologist",
            "Naturalist",
            "Occultist",
            "Illuminist",
            "Sophist",
            "Theologist",
            "Polymath",
            "Wannabe",
            "Bit Player",
            "Young Hopeful",
            "Rising Star",
            "Respected Artiste",
            "Cult Heroine",
            "Mover and Shaker",
            "Big Shot",
            "Major Player",
            "Phenomenon",
            "Backpacker",
            "Happy Camper",
            "Outdoorswoman",
            "Forest Dweller",
            "Wild Child",
            "Survivalist",
            "Bushcraftswoman",
            "Talented Tracker",
            "Pathfinder",
            "Queen of the Jungle",
            "Heiress of Heroes",
            "Majesty of Midenhall",
            "Future King of Cannock",
            "Moonbrooke Maiden",
            "Bonnie Burland Boy",
            "Tomboy Tsarevna",
            "Tutor of Tsarevna",
            "Most Holiest Priest",
            "Quare Feen",
            "Dramatic Dancer",
            "Foxy Fortune-Teller",
            "Best Friend Bride",
            "Well-Bred Bride",
            "Bossy Bride",
            "Punk-Haired Pugilist",
            "Elegant Oneiromancer",
            "Devil-May-Care Mage",
            "Reckless Royal",
            "Mayor's Heir",
            "Cursed King",
            "The Guv'nor",
            "Highly Strung Heiress",
            "Tasty Templar",
            "PASSION Personified",
            "Femme Fatale",
            "Bane of Baramos",
            "Chosen One",
            "Heavenly Groom",
            "Dream Warrior",
            "Estard's Finest",
            "Trodain Royal Guard",
            "Stella Artiste",
            "Stereotypical Sage",
            "Exemplary Luminary",
            "Textbook Trooper",
            "Prototypical Priest",
            "Model Minstrel",
            "Stock Stealer",
            "Fadiator",
            "Everyday Knight",
            "Paradigmatic Pugilist",
            "Average Armamentalist",
            "Classic Caster",
            "Regular Ranger",
            "Light-Speed Champion",
            "Hot to Trot",
            "Sleeper on the Job",
            "Easy Rider",
            "Exterminator",
            "Shopaholic",
            "Pacifist",
            "Socialite",
            "Philanthropist",
            "Cartographer",
            "Mighty Inviter",
            "Entitled Adventurer",
            "Completely Potty",
            "Zoologist",
            "Punchbag",
            "Snappy Dresser",
            "Recipe Researcher",
            null,
            "Moneybags",
            "Grievous Angel",
            "Monster Masher",
            "Fleet Completer",
            "Steady Edwina",
            "Party Hopper",
            "Immaculate Completion",
            "Guardian Angel",
            "Lionheart",
            "Sent From Above",
            "Watched-Over One",
            "Storied Saviour"
        };
        for (var index = 0; index < strArray1.Length; ++index)
            if (strArray1[index] != null)
                _list.Add(new TitleElement(strArray1[index], strArray2[index], index + 2));
        MaxDataIndex = strArray1.Length - 1;
    }

    public static int MaxDataIndex { get; }

    public static ReadOnlyCollection<TitleElement> List => _list.AsReadOnly();

    public static TitleElement GetTitleElement(int dataIndex)
    {
        foreach (var titleElement in _list)
            if (titleElement.DataIndex == dataIndex)
                return titleElement;
        return null;
    }
}